import type { DialectMetadata } from "../types/dialect";

// Generated by scripts/import-dialect-metadata.mjs.
// Review before using as linguistic evidence; external databases are auxiliary indexes.
export const dialectMetadata: DialectMetadata[] = [
  {
    "dialectId": "beijing_mandarin",
    "aliases": [
      "北京官话",
      "北京话",
      "Beijing Mandarin"
    ],
    "englishName": "Beijing Mandarin",
    "glottocode": "beij1234",
    "wikidataId": "Q1147606",
    "iso6393": "cmn",
    "parentGlottocode": "mand1415",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Mandarin Chinese",
      "Beijing Mandarin"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/beij1234",
      "https://glottolog.org/resource/languoid/id/mand1415",
      "https://www.wikidata.org/wiki/Q1147606"
    ],
    "phonologySource": "PHOIBLE",
    "phoibleInventoryIds": [
      "1047",
      "16",
      "2457",
      "286"
    ],
    "phonemeSample": [
      "cç",
      "cçʰ",
      "f",
      "j",
      "k",
      "kʰ",
      "l",
      "m",
      "n",
      "p",
      "pʰ",
      "s",
      "t",
      "ts",
      "tsʰ",
      "tʰ",
      "w",
      "w˞",
      "ç",
      "ŋ",
      "ɥ",
      "ɰ",
      "ʂ",
      "ʈʂ",
      "ʈʂʰ",
      "ʐ",
      "χ",
      "˥",
      "˥˦",
      "˧˥",
      "˧˨˥",
      "a"
    ],
    "notes": "dialect of Beijing Mandarin spoken in the capital of the PRC"
  },
  {
    "dialectId": "northeast_mandarin",
    "aliases": [
      "东北官话",
      "Northeastern Mandarin"
    ],
    "englishName": "Northeastern Mandarin",
    "glottocode": "nort3283",
    "wikidataId": "Q9192",
    "iso6393": "cmn",
    "parentGlottocode": "mand1415",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Mandarin Chinese",
      "Northeastern Mandarin"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/nort3283",
      "https://glottolog.org/resource/languoid/id/mand1415",
      "https://www.wikidata.org/wiki/Q9192"
    ],
    "phonologySource": "PHOIBLE",
    "phoibleInventoryIds": [
      "1047",
      "16",
      "2457",
      "286"
    ],
    "phonemeSample": [
      "cç",
      "cçʰ",
      "f",
      "j",
      "k",
      "kʰ",
      "l",
      "m",
      "n",
      "p",
      "pʰ",
      "s",
      "t",
      "ts",
      "tsʰ",
      "tʰ",
      "w",
      "w˞",
      "ç",
      "ŋ",
      "ɥ",
      "ɰ",
      "ʂ",
      "ʈʂ",
      "ʈʂʰ",
      "ʐ",
      "χ",
      "˥",
      "˥˦",
      "˧˥",
      "˧˨˥",
      "a"
    ],
    "notes": "major branch of Chinese spoken across most of northern and southwestern China"
  },
  {
    "dialectId": "jilu_mandarin",
    "aliases": [
      "冀鲁官话",
      "Jilu Mandarin"
    ],
    "englishName": "Jilu Mandarin",
    "wikidataId": "Q9192",
    "iso6393": "cmn",
    "parentGlottocode": "mand1415",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Mandarin Chinese"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/mand1415",
      "https://www.wikidata.org/wiki/Q9192"
    ],
    "phonologySource": "PHOIBLE",
    "phoibleInventoryIds": [
      "1047",
      "16",
      "2457",
      "286"
    ],
    "phonemeSample": [
      "cç",
      "cçʰ",
      "f",
      "j",
      "k",
      "kʰ",
      "l",
      "m",
      "n",
      "p",
      "pʰ",
      "s",
      "t",
      "ts",
      "tsʰ",
      "tʰ",
      "w",
      "w˞",
      "ç",
      "ŋ",
      "ɥ",
      "ɰ",
      "ʂ",
      "ʈʂ",
      "ʈʂʰ",
      "ʐ",
      "χ",
      "˥",
      "˥˦",
      "˧˥",
      "˧˨˥",
      "a"
    ],
    "notes": "major branch of Chinese spoken across most of northern and southwestern China"
  },
  {
    "dialectId": "jiaoliao_mandarin",
    "aliases": [
      "胶辽官话",
      "Jiaoliao Mandarin"
    ],
    "englishName": "Jiaoliao Mandarin",
    "wikidataId": "Q9192",
    "iso6393": "cmn",
    "parentGlottocode": "mand1415",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Mandarin Chinese"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/mand1415",
      "https://www.wikidata.org/wiki/Q9192"
    ],
    "phonologySource": "PHOIBLE",
    "phoibleInventoryIds": [
      "1047",
      "16",
      "2457",
      "286"
    ],
    "phonemeSample": [
      "cç",
      "cçʰ",
      "f",
      "j",
      "k",
      "kʰ",
      "l",
      "m",
      "n",
      "p",
      "pʰ",
      "s",
      "t",
      "ts",
      "tsʰ",
      "tʰ",
      "w",
      "w˞",
      "ç",
      "ŋ",
      "ɥ",
      "ɰ",
      "ʂ",
      "ʈʂ",
      "ʈʂʰ",
      "ʐ",
      "χ",
      "˥",
      "˥˦",
      "˧˥",
      "˧˨˥",
      "a"
    ],
    "notes": "major branch of Chinese spoken across most of northern and southwestern China"
  },
  {
    "dialectId": "zhongyuan_mandarin",
    "aliases": [
      "中原官话",
      "Central Plains Mandarin"
    ],
    "englishName": "Central Plains Mandarin",
    "wikidataId": "Q9192",
    "iso6393": "cmn",
    "parentGlottocode": "mand1415",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Mandarin Chinese"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/mand1415",
      "https://www.wikidata.org/wiki/Q9192"
    ],
    "phonologySource": "PHOIBLE",
    "phoibleInventoryIds": [
      "1047",
      "16",
      "2457",
      "286"
    ],
    "phonemeSample": [
      "cç",
      "cçʰ",
      "f",
      "j",
      "k",
      "kʰ",
      "l",
      "m",
      "n",
      "p",
      "pʰ",
      "s",
      "t",
      "ts",
      "tsʰ",
      "tʰ",
      "w",
      "w˞",
      "ç",
      "ŋ",
      "ɥ",
      "ɰ",
      "ʂ",
      "ʈʂ",
      "ʈʂʰ",
      "ʐ",
      "χ",
      "˥",
      "˥˦",
      "˧˥",
      "˧˨˥",
      "a"
    ],
    "notes": "major branch of Chinese spoken across most of northern and southwestern China"
  },
  {
    "dialectId": "lanyin_mandarin",
    "aliases": [
      "兰银官话",
      "Lan-Yin Mandarin"
    ],
    "englishName": "Lan-Yin Mandarin",
    "wikidataId": "Q9192",
    "iso6393": "cmn",
    "parentGlottocode": "mand1415",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Mandarin Chinese"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/mand1415",
      "https://www.wikidata.org/wiki/Q9192"
    ],
    "phonologySource": "PHOIBLE",
    "phoibleInventoryIds": [
      "1047",
      "16",
      "2457",
      "286"
    ],
    "phonemeSample": [
      "cç",
      "cçʰ",
      "f",
      "j",
      "k",
      "kʰ",
      "l",
      "m",
      "n",
      "p",
      "pʰ",
      "s",
      "t",
      "ts",
      "tsʰ",
      "tʰ",
      "w",
      "w˞",
      "ç",
      "ŋ",
      "ɥ",
      "ɰ",
      "ʂ",
      "ʈʂ",
      "ʈʂʰ",
      "ʐ",
      "χ",
      "˥",
      "˥˦",
      "˧˥",
      "˧˨˥",
      "a"
    ],
    "notes": "major branch of Chinese spoken across most of northern and southwestern China"
  },
  {
    "dialectId": "jianghuai_mandarin",
    "aliases": [
      "江淮官话",
      "Jianghuai Mandarin"
    ],
    "englishName": "Jianghuai Mandarin",
    "wikidataId": "Q9192",
    "iso6393": "cmn",
    "parentGlottocode": "mand1415",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Mandarin Chinese"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/mand1415",
      "https://www.wikidata.org/wiki/Q9192"
    ],
    "phonologySource": "PHOIBLE",
    "phoibleInventoryIds": [
      "1047",
      "16",
      "2457",
      "286"
    ],
    "phonemeSample": [
      "cç",
      "cçʰ",
      "f",
      "j",
      "k",
      "kʰ",
      "l",
      "m",
      "n",
      "p",
      "pʰ",
      "s",
      "t",
      "ts",
      "tsʰ",
      "tʰ",
      "w",
      "w˞",
      "ç",
      "ŋ",
      "ɥ",
      "ɰ",
      "ʂ",
      "ʈʂ",
      "ʈʂʰ",
      "ʐ",
      "χ",
      "˥",
      "˥˦",
      "˧˥",
      "˧˨˥",
      "a"
    ],
    "notes": "major branch of Chinese spoken across most of northern and southwestern China"
  },
  {
    "dialectId": "southwest_mandarin",
    "aliases": [
      "西南官话",
      "Southwestern Mandarin"
    ],
    "englishName": "Southwestern Mandarin",
    "wikidataId": "Q9192",
    "iso6393": "cmn",
    "parentGlottocode": "mand1415",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Mandarin Chinese"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/mand1415",
      "https://www.wikidata.org/wiki/Q9192"
    ],
    "phonologySource": "PHOIBLE",
    "phoibleInventoryIds": [
      "1047",
      "16",
      "2457",
      "286"
    ],
    "phonemeSample": [
      "cç",
      "cçʰ",
      "f",
      "j",
      "k",
      "kʰ",
      "l",
      "m",
      "n",
      "p",
      "pʰ",
      "s",
      "t",
      "ts",
      "tsʰ",
      "tʰ",
      "w",
      "w˞",
      "ç",
      "ŋ",
      "ɥ",
      "ɰ",
      "ʂ",
      "ʈʂ",
      "ʈʂʰ",
      "ʐ",
      "χ",
      "˥",
      "˥˦",
      "˧˥",
      "˧˨˥",
      "a"
    ],
    "notes": "major branch of Chinese spoken across most of northern and southwestern China"
  },
  {
    "dialectId": "shanghai_wu",
    "aliases": [
      "上海话",
      "Shanghainese"
    ],
    "englishName": "Shanghainese",
    "glottocode": "shan1293",
    "wikidataId": "Q36718",
    "iso6393": "wuu",
    "parentGlottocode": "wuch1236",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Wu Chinese",
      "Shanghainese"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/shan1293",
      "https://glottolog.org/resource/languoid/id/wuch1236",
      "https://www.wikidata.org/wiki/Q36718"
    ],
    "phonologySource": "PHOIBLE",
    "phoibleInventoryIds": [
      "17",
      "622"
    ],
    "phonemeSample": [
      "b̤̥",
      "d̤̥",
      "f",
      "h",
      "j",
      "k",
      "kʰ",
      "l",
      "m",
      "m̩",
      "n",
      "p",
      "pʰ",
      "s",
      "t",
      "ts",
      "tsʰ",
      "tz̤̥",
      "tʰ",
      "v",
      "w",
      "z",
      "z̞̩",
      "ŋ",
      "ŋ̩",
      "ɡ̤̥",
      "ɦ",
      "ɻ",
      "ʔ",
      "˥",
      "˥˧˥",
      "˦"
    ],
    "notes": "Chinese variant-language named for Shanghai and its region"
  },
  {
    "dialectId": "cantonese_guangfu",
    "aliases": [
      "粤语",
      "广州话",
      "Cantonese"
    ],
    "englishName": "Cantonese",
    "glottocode": "cant1236",
    "wikidataId": "Q9186",
    "iso6393": "yue",
    "parentGlottocode": "yuec1235",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Yue Chinese",
      "Cantonese"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/cant1236",
      "https://glottolog.org/resource/languoid/id/yuec1235",
      "https://www.wikidata.org/wiki/Q9186"
    ],
    "phonologySource": "PHOIBLE",
    "phoibleInventoryIds": [
      "19",
      "2166",
      "2309",
      "642"
    ],
    "phonemeSample": [
      "f",
      "h",
      "j",
      "k",
      "kʰ",
      "kʷ",
      "kʷʰ",
      "l",
      "l̥",
      "m",
      "m̩",
      "n",
      "p",
      "pʰ",
      "t",
      "tʰ",
      "t̠ʃ",
      "t̠ʃʰ",
      "w",
      "ŋ",
      "ŋ̩",
      "ʃ",
      "˥",
      "˥˦",
      "˧",
      "˧˩̰",
      "˩",
      "a",
      "i",
      "u",
      "æ",
      "ɔ"
    ],
    "notes": "variety of Yue Chinese spoken in Guangzhou, Hong Kong, and Macau"
  },
  {
    "dialectId": "minnan_xiamen",
    "aliases": [
      "闽南语",
      "厦门话",
      "Hokkien",
      "Southern Min"
    ],
    "englishName": "Min Nan Chinese",
    "glottocode": "minn1241",
    "wikidataId": "Q36495",
    "iso6393": "nan",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Min Nan Chinese"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/minn1241",
      "https://www.wikidata.org/wiki/Q36495"
    ],
    "phonologySource": "PHOIBLE",
    "phoibleInventoryIds": [
      "481"
    ],
    "phonemeSample": [
      "b",
      "d̠ʒ",
      "d̪z̪|dz",
      "d̪|d",
      "h",
      "k",
      "kʰ",
      "m",
      "n̪|n",
      "p",
      "pʰ",
      "s̪|s",
      "t̪s̪|ts",
      "t̪s̪ʰ|tsʰ",
      "t̪|t",
      "t̪ʰ|tʰ",
      "ŋ",
      "ɡ",
      "ʔ",
      "a",
      "e",
      "i",
      "o",
      "u",
      "ɔ"
    ],
    "notes": "branch of the Min Chinese language"
  },
  {
    "dialectId": "mindong_fuzhou",
    "aliases": [
      "闽东语",
      "福州话",
      "Eastern Min",
      "Fuzhou dialect"
    ],
    "englishName": "Eastern Nahuatl",
    "glottocode": "east2720",
    "wikidataId": "Q5330379",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Eastern Nahuatl"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/east2720",
      "https://www.wikidata.org/wiki/Q5330379"
    ],
    "phonologySource": "PHOIBLE inventory not found for this seed",
    "phoibleInventoryIds": [],
    "phonemeSample": [],
    "notes": "language"
  },
  {
    "dialectId": "minbei_general",
    "aliases": [
      "闽北语",
      "Northern Min"
    ],
    "englishName": "Northern Gelao",
    "glottocode": "nort3188",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Northern Gelao"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/nort3188"
    ],
    "phonologySource": "PHOIBLE inventory not found for this seed",
    "phoibleInventoryIds": [],
    "phonemeSample": [],
    "notes": "Imported auxiliary metadata; verify before citing in analysis."
  },
  {
    "dialectId": "minzhong_general",
    "aliases": [
      "闽中语",
      "Central Min"
    ],
    "englishName": "Central Melanau",
    "glottocode": "cent2101",
    "wikidataId": "Q18638319",
    "iso6393": "mel",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Central Melanau"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/cent2101",
      "https://www.wikidata.org/wiki/Q18638319"
    ],
    "phonologySource": "PHOIBLE inventory not found for this seed",
    "phoibleInventoryIds": [],
    "phonemeSample": [],
    "notes": "language"
  },
  {
    "dialectId": "puxian_min",
    "aliases": [
      "莆仙语",
      "Puxian Min"
    ],
    "englishName": "Pu-Xian Chinese",
    "glottocode": "puxi1243",
    "wikidataId": "Q56583",
    "iso6393": "cpx",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Pu-Xian Chinese"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/puxi1243",
      "https://www.wikidata.org/wiki/Q56583"
    ],
    "phonologySource": "PHOIBLE inventory not found for this seed",
    "phoibleInventoryIds": [],
    "phonemeSample": [],
    "notes": "language"
  },
  {
    "dialectId": "chaoshan_min",
    "aliases": [
      "潮汕话",
      "Teochew",
      "Chaoshan Min"
    ],
    "englishName": "Teochew",
    "wikidataId": "Q36495",
    "iso6393": "nan",
    "parentGlottocode": "minn1241",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Min Nan Chinese"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/minn1241",
      "https://www.wikidata.org/wiki/Q36495"
    ],
    "phonologySource": "PHOIBLE",
    "phoibleInventoryIds": [
      "481"
    ],
    "phonemeSample": [
      "b",
      "d̠ʒ",
      "d̪z̪|dz",
      "d̪|d",
      "h",
      "k",
      "kʰ",
      "m",
      "n̪|n",
      "p",
      "pʰ",
      "s̪|s",
      "t̪s̪|ts",
      "t̪s̪ʰ|tsʰ",
      "t̪|t",
      "t̪ʰ|tʰ",
      "ŋ",
      "ɡ",
      "ʔ",
      "a",
      "e",
      "i",
      "o",
      "u",
      "ɔ"
    ],
    "notes": "branch of the Min Chinese language"
  },
  {
    "dialectId": "leizhou_min",
    "aliases": [
      "雷州话",
      "Leizhou Min"
    ],
    "englishName": "Leizhou Min",
    "wikidataId": "Q36495",
    "iso6393": "nan",
    "parentGlottocode": "minn1241",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Min Nan Chinese"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/minn1241",
      "https://www.wikidata.org/wiki/Q36495"
    ],
    "phonologySource": "PHOIBLE",
    "phoibleInventoryIds": [
      "481"
    ],
    "phonemeSample": [
      "b",
      "d̠ʒ",
      "d̪z̪|dz",
      "d̪|d",
      "h",
      "k",
      "kʰ",
      "m",
      "n̪|n",
      "p",
      "pʰ",
      "s̪|s",
      "t̪s̪|ts",
      "t̪s̪ʰ|tsʰ",
      "t̪|t",
      "t̪ʰ|tʰ",
      "ŋ",
      "ɡ",
      "ʔ",
      "a",
      "e",
      "i",
      "o",
      "u",
      "ɔ"
    ],
    "notes": "branch of the Min Chinese language"
  },
  {
    "dialectId": "gan_nanchang",
    "aliases": [
      "赣语",
      "南昌话",
      "Gan Chinese"
    ],
    "englishName": "Gan Chinese",
    "glottocode": "ganc1239",
    "wikidataId": "Q33475",
    "iso6393": "gan",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Gan Chinese"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/ganc1239",
      "https://www.wikidata.org/wiki/Q33475"
    ],
    "phonologySource": "PHOIBLE inventory not found for this seed",
    "phoibleInventoryIds": [],
    "phonemeSample": [],
    "notes": "member of the Sinitic languages of the Sino-Tibetan language family spoken as the native language by the people in the Jiangxi province of China"
  },
  {
    "dialectId": "xiang_changsha",
    "aliases": [
      "湘语",
      "长沙话",
      "Xiang Chinese"
    ],
    "englishName": "Xiang Chinese",
    "glottocode": "xian1251",
    "wikidataId": "Q13220",
    "iso6393": "hsn",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Xiang Chinese"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/xian1251",
      "https://www.wikidata.org/wiki/Q13220"
    ],
    "phonologySource": "PHOIBLE inventory not found for this seed",
    "phoibleInventoryIds": [],
    "phonemeSample": [],
    "notes": "Chinese language spoken mainly in Hunan province"
  },
  {
    "dialectId": "jin_taiyuan",
    "aliases": [
      "晋语",
      "太原话",
      "Jin Chinese"
    ],
    "englishName": "Jinyu Chinese",
    "glottocode": "jiny1235",
    "wikidataId": "Q56479",
    "iso6393": "cjy",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Jinyu Chinese"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/jiny1235",
      "https://www.wikidata.org/wiki/Q56479"
    ],
    "phonologySource": "PHOIBLE inventory not found for this seed",
    "phoibleInventoryIds": [],
    "phonemeSample": [],
    "notes": "variety of Chinese spoken in northern China"
  },
  {
    "dialectId": "hakka_meixian",
    "aliases": [
      "客家话",
      "梅县话",
      "Hakka Chinese"
    ],
    "englishName": "Hakka Chinese",
    "glottocode": "hakk1236",
    "wikidataId": "Q33375",
    "iso6393": "hak",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Hakka Chinese"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/hakk1236",
      "https://www.wikidata.org/wiki/Q33375"
    ],
    "phonologySource": "PHOIBLE",
    "phoibleInventoryIds": [
      "18",
      "2165",
      "2323",
      "350"
    ],
    "phonemeSample": [
      "f",
      "h",
      "j",
      "k̟",
      "k̟ʰ",
      "l",
      "mb",
      "m̩",
      "nd",
      "p",
      "pʰ",
      "s",
      "t",
      "ts",
      "tsʰ",
      "tʰ",
      "w",
      "z̞̩",
      "ŋɡ̟",
      "ŋ̩",
      "ʔ",
      "˥",
      "˧",
      "˧˩",
      "˩",
      "a",
      "i",
      "u",
      "æ",
      "ɔ",
      "ɛ",
      "k"
    ],
    "notes": "primary branch of Chinese originating in Southern China"
  },
  {
    "dialectId": "hui_general",
    "aliases": [
      "徽语",
      "Huizhou Chinese"
    ],
    "englishName": "Hui Chinese",
    "glottocode": "huiz1242",
    "wikidataId": "Q56546",
    "iso6393": "czh",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Hui Chinese"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/huiz1242",
      "https://www.wikidata.org/wiki/Q56546"
    ],
    "phonologySource": "PHOIBLE inventory not found for this seed",
    "phoibleInventoryIds": [],
    "phonemeSample": [],
    "notes": "Sinitic language"
  },
  {
    "dialectId": "pinghua_general",
    "aliases": [
      "平话",
      "Pinghua"
    ],
    "englishName": "Pinghua",
    "glottocode": "ping1245",
    "wikidataId": "Q2735715",
    "classification": [
      "Sino-Tibetan",
      "Sinitic",
      "Pinghua"
    ],
    "referenceLinks": [
      "https://glottolog.org/resource/languoid/id/ping1245",
      "https://www.wikidata.org/wiki/Q2735715"
    ],
    "phonologySource": "PHOIBLE inventory not found for this seed",
    "phoibleInventoryIds": [],
    "phonemeSample": [],
    "notes": "Chinese language spoken mainly in parts of the Guangxi Zhuang Autonomous Region, with some speakers in Yunnan province"
  },
  {
    "dialectId": "other_languages",
    "aliases": [
      "其他语言/方言待细分"
    ],
    "classification": [
      "Sino-Tibetan",
      "Sinitic"
    ],
    "referenceLinks": [],
    "phonologySource": "PHOIBLE inventory not found for this seed",
    "phoibleInventoryIds": [],
    "phonemeSample": [],
    "notes": "Placeholder for non-Sinitic or not-yet-classified resources."
  }
];
