import type { Region } from "../types/dialect";

// Generated by scripts/generate-map-index.mjs from public/geojson/china/*.json.
export const generatedRegions: Region[] = [
  {
    "code": "100000",
    "name": "全国",
    "level": "country",
    "geoJsonUrl": "/geojson/china/provinces.json",
    "center": [
      104,
      35
    ]
  },
  {
    "code": "110000",
    "name": "北京市",
    "level": "province",
    "parentCode": "100000",
    "center": [
      116.405285,
      39.904989
    ],
    "geoJsonUrl": "/geojson/china/110000.json"
  },
  {
    "code": "120000",
    "name": "天津市",
    "level": "province",
    "parentCode": "100000",
    "center": [
      117.190182,
      39.125596
    ],
    "geoJsonUrl": "/geojson/china/120000.json"
  },
  {
    "code": "130000",
    "name": "河北省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      114.502461,
      38.045474
    ],
    "geoJsonUrl": "/geojson/china/130000.json"
  },
  {
    "code": "140000",
    "name": "山西省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      112.549248,
      37.857014
    ],
    "geoJsonUrl": "/geojson/china/140000.json"
  },
  {
    "code": "150000",
    "name": "内蒙古自治区",
    "level": "province",
    "parentCode": "100000",
    "center": [
      111.670801,
      40.818311
    ],
    "geoJsonUrl": "/geojson/china/150000.json"
  },
  {
    "code": "210000",
    "name": "辽宁省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      123.429096,
      41.796767
    ],
    "geoJsonUrl": "/geojson/china/210000.json"
  },
  {
    "code": "220000",
    "name": "吉林省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      125.3245,
      43.886841
    ],
    "geoJsonUrl": "/geojson/china/220000.json"
  },
  {
    "code": "230000",
    "name": "黑龙江省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      126.642464,
      45.756967
    ],
    "geoJsonUrl": "/geojson/china/230000.json"
  },
  {
    "code": "310000",
    "name": "上海市",
    "level": "province",
    "parentCode": "100000",
    "center": [
      121.472644,
      31.231706
    ],
    "geoJsonUrl": "/geojson/china/310000.json"
  },
  {
    "code": "320000",
    "name": "江苏省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      118.767413,
      32.041544
    ],
    "geoJsonUrl": "/geojson/china/320000.json"
  },
  {
    "code": "330000",
    "name": "浙江省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      120.153576,
      30.287459
    ],
    "geoJsonUrl": "/geojson/china/330000.json"
  },
  {
    "code": "340000",
    "name": "安徽省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      117.283042,
      31.86119
    ],
    "geoJsonUrl": "/geojson/china/340000.json"
  },
  {
    "code": "350000",
    "name": "福建省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      119.306239,
      26.075302
    ],
    "geoJsonUrl": "/geojson/china/350000.json"
  },
  {
    "code": "360000",
    "name": "江西省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      115.892151,
      28.676493
    ],
    "geoJsonUrl": "/geojson/china/360000.json"
  },
  {
    "code": "370000",
    "name": "山东省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      117.000923,
      36.675807
    ],
    "geoJsonUrl": "/geojson/china/370000.json"
  },
  {
    "code": "410000",
    "name": "河南省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      113.665412,
      34.757975
    ],
    "geoJsonUrl": "/geojson/china/410000.json"
  },
  {
    "code": "420000",
    "name": "湖北省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      114.298572,
      30.584355
    ],
    "geoJsonUrl": "/geojson/china/420000.json"
  },
  {
    "code": "430000",
    "name": "湖南省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      112.982279,
      28.19409
    ],
    "geoJsonUrl": "/geojson/china/430000.json"
  },
  {
    "code": "440000",
    "name": "广东省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      113.280637,
      23.125178
    ],
    "geoJsonUrl": "/geojson/china/440000.json"
  },
  {
    "code": "450000",
    "name": "广西壮族自治区",
    "level": "province",
    "parentCode": "100000",
    "center": [
      108.320004,
      22.82402
    ],
    "geoJsonUrl": "/geojson/china/450000.json"
  },
  {
    "code": "460000",
    "name": "海南省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      110.33119,
      20.031971
    ],
    "geoJsonUrl": "/geojson/china/460000.json"
  },
  {
    "code": "500000",
    "name": "重庆市",
    "level": "province",
    "parentCode": "100000",
    "center": [
      106.504962,
      29.533155
    ],
    "geoJsonUrl": "/geojson/china/500000.json"
  },
  {
    "code": "510000",
    "name": "四川省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      104.065735,
      30.659462
    ],
    "geoJsonUrl": "/geojson/china/510000.json"
  },
  {
    "code": "520000",
    "name": "贵州省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      106.713478,
      26.578343
    ],
    "geoJsonUrl": "/geojson/china/520000.json"
  },
  {
    "code": "530000",
    "name": "云南省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      102.712251,
      25.040609
    ],
    "geoJsonUrl": "/geojson/china/530000.json"
  },
  {
    "code": "540000",
    "name": "西藏自治区",
    "level": "province",
    "parentCode": "100000",
    "center": [
      91.132212,
      29.660361
    ],
    "geoJsonUrl": "/geojson/china/540000.json"
  },
  {
    "code": "610000",
    "name": "陕西省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      108.948024,
      34.263161
    ],
    "geoJsonUrl": "/geojson/china/610000.json"
  },
  {
    "code": "620000",
    "name": "甘肃省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      103.823557,
      36.058039
    ],
    "geoJsonUrl": "/geojson/china/620000.json"
  },
  {
    "code": "630000",
    "name": "青海省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      101.778916,
      36.623178
    ],
    "geoJsonUrl": "/geojson/china/630000.json"
  },
  {
    "code": "640000",
    "name": "宁夏回族自治区",
    "level": "province",
    "parentCode": "100000",
    "center": [
      106.278179,
      38.46637
    ],
    "geoJsonUrl": "/geojson/china/640000.json"
  },
  {
    "code": "650000",
    "name": "新疆维吾尔自治区",
    "level": "province",
    "parentCode": "100000",
    "center": [
      87.617733,
      43.792818
    ],
    "geoJsonUrl": "/geojson/china/650000.json"
  },
  {
    "code": "710000",
    "name": "台湾省",
    "level": "province",
    "parentCode": "100000",
    "center": [
      121.509062,
      25.044332
    ],
    "geoJsonUrl": "/geojson/china/710000.json"
  },
  {
    "code": "810000",
    "name": "香港特别行政区",
    "level": "province",
    "parentCode": "100000",
    "center": [
      114.173355,
      22.320048
    ],
    "geoJsonUrl": "/geojson/china/810000.json"
  },
  {
    "code": "820000",
    "name": "澳门特别行政区",
    "level": "province",
    "parentCode": "100000",
    "center": [
      113.54909,
      22.198951
    ],
    "geoJsonUrl": "/geojson/china/820000.json"
  },
  {
    "code": "110101",
    "name": "东城区",
    "level": "county",
    "parentCode": "110000",
    "center": [
      116.418757,
      39.917544
    ],
    "province": "北京市"
  },
  {
    "code": "110102",
    "name": "西城区",
    "level": "county",
    "parentCode": "110000",
    "center": [
      116.366794,
      39.915309
    ],
    "province": "北京市"
  },
  {
    "code": "110105",
    "name": "朝阳区",
    "level": "county",
    "parentCode": "110000",
    "center": [
      116.486409,
      39.921489
    ],
    "province": "北京市"
  },
  {
    "code": "110106",
    "name": "丰台区",
    "level": "county",
    "parentCode": "110000",
    "center": [
      116.286968,
      39.863642
    ],
    "province": "北京市"
  },
  {
    "code": "110107",
    "name": "石景山区",
    "level": "county",
    "parentCode": "110000",
    "center": [
      116.195445,
      39.914601
    ],
    "province": "北京市"
  },
  {
    "code": "110108",
    "name": "海淀区",
    "level": "county",
    "parentCode": "110000",
    "center": [
      116.310316,
      39.956074
    ],
    "province": "北京市"
  },
  {
    "code": "110109",
    "name": "门头沟区",
    "level": "county",
    "parentCode": "110000",
    "center": [
      116.105381,
      39.937183
    ],
    "province": "北京市"
  },
  {
    "code": "110111",
    "name": "房山区",
    "level": "county",
    "parentCode": "110000",
    "center": [
      116.139157,
      39.735535
    ],
    "province": "北京市"
  },
  {
    "code": "110112",
    "name": "通州区",
    "level": "county",
    "parentCode": "110000",
    "center": [
      116.658603,
      39.902486
    ],
    "province": "北京市"
  },
  {
    "code": "110113",
    "name": "顺义区",
    "level": "county",
    "parentCode": "110000",
    "center": [
      116.653525,
      40.128936
    ],
    "province": "北京市"
  },
  {
    "code": "110114",
    "name": "昌平区",
    "level": "county",
    "parentCode": "110000",
    "center": [
      116.235906,
      40.218085
    ],
    "province": "北京市"
  },
  {
    "code": "110115",
    "name": "大兴区",
    "level": "county",
    "parentCode": "110000",
    "center": [
      116.338033,
      39.728908
    ],
    "province": "北京市"
  },
  {
    "code": "110116",
    "name": "怀柔区",
    "level": "county",
    "parentCode": "110000",
    "center": [
      116.637122,
      40.324272
    ],
    "province": "北京市"
  },
  {
    "code": "110117",
    "name": "平谷区",
    "level": "county",
    "parentCode": "110000",
    "center": [
      117.112335,
      40.144783
    ],
    "province": "北京市"
  },
  {
    "code": "110118",
    "name": "密云区",
    "level": "county",
    "parentCode": "110000",
    "center": [
      116.843352,
      40.377362
    ],
    "province": "北京市"
  },
  {
    "code": "110119",
    "name": "延庆区",
    "level": "county",
    "parentCode": "110000",
    "center": [
      115.985006,
      40.465325
    ],
    "province": "北京市"
  },
  {
    "code": "120101",
    "name": "和平区",
    "level": "county",
    "parentCode": "120000",
    "center": [
      117.195907,
      39.118327
    ],
    "province": "天津市"
  },
  {
    "code": "120102",
    "name": "河东区",
    "level": "county",
    "parentCode": "120000",
    "center": [
      117.226568,
      39.122125
    ],
    "province": "天津市"
  },
  {
    "code": "120103",
    "name": "河西区",
    "level": "county",
    "parentCode": "120000",
    "center": [
      117.217536,
      39.101897
    ],
    "province": "天津市"
  },
  {
    "code": "120104",
    "name": "南开区",
    "level": "county",
    "parentCode": "120000",
    "center": [
      117.164143,
      39.120474
    ],
    "province": "天津市"
  },
  {
    "code": "120105",
    "name": "河北区",
    "level": "county",
    "parentCode": "120000",
    "center": [
      117.201569,
      39.156632
    ],
    "province": "天津市"
  },
  {
    "code": "120106",
    "name": "红桥区",
    "level": "county",
    "parentCode": "120000",
    "center": [
      117.163301,
      39.175066
    ],
    "province": "天津市"
  },
  {
    "code": "120110",
    "name": "东丽区",
    "level": "county",
    "parentCode": "120000",
    "center": [
      117.313967,
      39.087764
    ],
    "province": "天津市"
  },
  {
    "code": "120111",
    "name": "西青区",
    "level": "county",
    "parentCode": "120000",
    "center": [
      117.012247,
      39.139446
    ],
    "province": "天津市"
  },
  {
    "code": "120112",
    "name": "津南区",
    "level": "county",
    "parentCode": "120000",
    "center": [
      117.382549,
      38.989577
    ],
    "province": "天津市"
  },
  {
    "code": "120113",
    "name": "北辰区",
    "level": "county",
    "parentCode": "120000",
    "center": [
      117.13482,
      39.225555
    ],
    "province": "天津市"
  },
  {
    "code": "120114",
    "name": "武清区",
    "level": "county",
    "parentCode": "120000",
    "center": [
      117.057959,
      39.376925
    ],
    "province": "天津市"
  },
  {
    "code": "120115",
    "name": "宝坻区",
    "level": "county",
    "parentCode": "120000",
    "center": [
      117.308094,
      39.716965
    ],
    "province": "天津市"
  },
  {
    "code": "120116",
    "name": "滨海新区",
    "level": "county",
    "parentCode": "120000",
    "center": [
      117.654173,
      39.032846
    ],
    "province": "天津市"
  },
  {
    "code": "120117",
    "name": "宁河区",
    "level": "county",
    "parentCode": "120000",
    "center": [
      117.82828,
      39.328886
    ],
    "province": "天津市"
  },
  {
    "code": "120118",
    "name": "静海区",
    "level": "county",
    "parentCode": "120000",
    "center": [
      116.925304,
      38.935671
    ],
    "province": "天津市"
  },
  {
    "code": "120119",
    "name": "蓟州区",
    "level": "county",
    "parentCode": "120000",
    "center": [
      117.407449,
      40.045342
    ],
    "province": "天津市"
  },
  {
    "code": "130100",
    "name": "石家庄市",
    "level": "city",
    "parentCode": "130000",
    "center": [
      114.502461,
      38.045474
    ],
    "province": "河北省"
  },
  {
    "code": "130200",
    "name": "唐山市",
    "level": "city",
    "parentCode": "130000",
    "center": [
      118.175393,
      39.635113
    ],
    "province": "河北省"
  },
  {
    "code": "130300",
    "name": "秦皇岛市",
    "level": "city",
    "parentCode": "130000",
    "center": [
      119.586579,
      39.942531
    ],
    "province": "河北省"
  },
  {
    "code": "130400",
    "name": "邯郸市",
    "level": "city",
    "parentCode": "130000",
    "center": [
      114.490686,
      36.612273
    ],
    "province": "河北省"
  },
  {
    "code": "130500",
    "name": "邢台市",
    "level": "city",
    "parentCode": "130000",
    "center": [
      114.508851,
      37.0682
    ],
    "province": "河北省"
  },
  {
    "code": "130600",
    "name": "保定市",
    "level": "city",
    "parentCode": "130000",
    "center": [
      115.482331,
      38.867657
    ],
    "province": "河北省"
  },
  {
    "code": "130700",
    "name": "张家口市",
    "level": "city",
    "parentCode": "130000",
    "center": [
      114.884091,
      40.811901
    ],
    "province": "河北省"
  },
  {
    "code": "130800",
    "name": "承德市",
    "level": "city",
    "parentCode": "130000",
    "center": [
      117.939152,
      40.976204
    ],
    "province": "河北省"
  },
  {
    "code": "130900",
    "name": "沧州市",
    "level": "city",
    "parentCode": "130000",
    "center": [
      116.857461,
      38.310582
    ],
    "province": "河北省"
  },
  {
    "code": "131000",
    "name": "廊坊市",
    "level": "city",
    "parentCode": "130000",
    "center": [
      116.704441,
      39.523927
    ],
    "province": "河北省"
  },
  {
    "code": "131100",
    "name": "衡水市",
    "level": "city",
    "parentCode": "130000",
    "center": [
      115.665993,
      37.735097
    ],
    "province": "河北省"
  },
  {
    "code": "140100",
    "name": "太原市",
    "level": "city",
    "parentCode": "140000",
    "center": [
      112.549248,
      37.857014
    ],
    "province": "山西省"
  },
  {
    "code": "140200",
    "name": "大同市",
    "level": "city",
    "parentCode": "140000",
    "center": [
      113.295259,
      40.09031
    ],
    "province": "山西省"
  },
  {
    "code": "140300",
    "name": "阳泉市",
    "level": "city",
    "parentCode": "140000",
    "center": [
      113.583285,
      37.861188
    ],
    "province": "山西省"
  },
  {
    "code": "140400",
    "name": "长治市",
    "level": "city",
    "parentCode": "140000",
    "center": [
      113.113556,
      36.191112
    ],
    "province": "山西省"
  },
  {
    "code": "140500",
    "name": "晋城市",
    "level": "city",
    "parentCode": "140000",
    "center": [
      112.851274,
      35.497553
    ],
    "province": "山西省"
  },
  {
    "code": "140600",
    "name": "朔州市",
    "level": "city",
    "parentCode": "140000",
    "center": [
      112.433387,
      39.331261
    ],
    "province": "山西省"
  },
  {
    "code": "140700",
    "name": "晋中市",
    "level": "city",
    "parentCode": "140000",
    "center": [
      112.736465,
      37.696495
    ],
    "province": "山西省"
  },
  {
    "code": "140800",
    "name": "运城市",
    "level": "city",
    "parentCode": "140000",
    "center": [
      111.003957,
      35.022778
    ],
    "province": "山西省"
  },
  {
    "code": "140900",
    "name": "忻州市",
    "level": "city",
    "parentCode": "140000",
    "center": [
      112.733538,
      38.41769
    ],
    "province": "山西省"
  },
  {
    "code": "141000",
    "name": "临汾市",
    "level": "city",
    "parentCode": "140000",
    "center": [
      111.517973,
      36.08415
    ],
    "province": "山西省"
  },
  {
    "code": "141100",
    "name": "吕梁市",
    "level": "city",
    "parentCode": "140000",
    "center": [
      111.134335,
      37.524366
    ],
    "province": "山西省"
  },
  {
    "code": "150100",
    "name": "呼和浩特市",
    "level": "city",
    "parentCode": "150000",
    "center": [
      111.670801,
      40.818311
    ],
    "province": "内蒙古自治区"
  },
  {
    "code": "150200",
    "name": "包头市",
    "level": "city",
    "parentCode": "150000",
    "center": [
      109.840405,
      40.658168
    ],
    "province": "内蒙古自治区"
  },
  {
    "code": "150300",
    "name": "乌海市",
    "level": "city",
    "parentCode": "150000",
    "center": [
      106.825563,
      39.673734
    ],
    "province": "内蒙古自治区"
  },
  {
    "code": "150400",
    "name": "赤峰市",
    "level": "city",
    "parentCode": "150000",
    "center": [
      118.956806,
      42.275317
    ],
    "province": "内蒙古自治区"
  },
  {
    "code": "150500",
    "name": "通辽市",
    "level": "city",
    "parentCode": "150000",
    "center": [
      122.263119,
      43.617429
    ],
    "province": "内蒙古自治区"
  },
  {
    "code": "150600",
    "name": "鄂尔多斯市",
    "level": "city",
    "parentCode": "150000",
    "center": [
      109.99029,
      39.817179
    ],
    "province": "内蒙古自治区"
  },
  {
    "code": "150700",
    "name": "呼伦贝尔市",
    "level": "city",
    "parentCode": "150000",
    "center": [
      119.758168,
      49.215333
    ],
    "province": "内蒙古自治区"
  },
  {
    "code": "150800",
    "name": "巴彦淖尔市",
    "level": "city",
    "parentCode": "150000",
    "center": [
      107.416959,
      40.757402
    ],
    "province": "内蒙古自治区"
  },
  {
    "code": "150900",
    "name": "乌兰察布市",
    "level": "city",
    "parentCode": "150000",
    "center": [
      113.114543,
      41.034126
    ],
    "province": "内蒙古自治区"
  },
  {
    "code": "152200",
    "name": "兴安盟",
    "level": "city",
    "parentCode": "150000",
    "center": [
      122.070317,
      46.076268
    ],
    "province": "内蒙古自治区"
  },
  {
    "code": "152500",
    "name": "锡林郭勒盟",
    "level": "city",
    "parentCode": "150000",
    "center": [
      116.090996,
      43.944018
    ],
    "province": "内蒙古自治区"
  },
  {
    "code": "152900",
    "name": "阿拉善盟",
    "level": "city",
    "parentCode": "150000",
    "center": [
      105.706422,
      38.844814
    ],
    "province": "内蒙古自治区"
  },
  {
    "code": "210100",
    "name": "沈阳市",
    "level": "city",
    "parentCode": "210000",
    "center": [
      123.429096,
      41.796767
    ],
    "province": "辽宁省"
  },
  {
    "code": "210200",
    "name": "大连市",
    "level": "city",
    "parentCode": "210000",
    "center": [
      121.618622,
      38.91459
    ],
    "province": "辽宁省"
  },
  {
    "code": "210300",
    "name": "鞍山市",
    "level": "city",
    "parentCode": "210000",
    "center": [
      122.995632,
      41.110626
    ],
    "province": "辽宁省"
  },
  {
    "code": "210400",
    "name": "抚顺市",
    "level": "city",
    "parentCode": "210000",
    "center": [
      123.921109,
      41.875956
    ],
    "province": "辽宁省"
  },
  {
    "code": "210500",
    "name": "本溪市",
    "level": "city",
    "parentCode": "210000",
    "center": [
      123.770519,
      41.297909
    ],
    "province": "辽宁省"
  },
  {
    "code": "210600",
    "name": "丹东市",
    "level": "city",
    "parentCode": "210000",
    "center": [
      124.383044,
      40.124296
    ],
    "province": "辽宁省"
  },
  {
    "code": "210700",
    "name": "锦州市",
    "level": "city",
    "parentCode": "210000",
    "center": [
      121.135742,
      41.119269
    ],
    "province": "辽宁省"
  },
  {
    "code": "210800",
    "name": "营口市",
    "level": "city",
    "parentCode": "210000",
    "center": [
      122.235151,
      40.667432
    ],
    "province": "辽宁省"
  },
  {
    "code": "210900",
    "name": "阜新市",
    "level": "city",
    "parentCode": "210000",
    "center": [
      121.648962,
      42.011796
    ],
    "province": "辽宁省"
  },
  {
    "code": "211000",
    "name": "辽阳市",
    "level": "city",
    "parentCode": "210000",
    "center": [
      123.18152,
      41.269402
    ],
    "province": "辽宁省"
  },
  {
    "code": "211100",
    "name": "盘锦市",
    "level": "city",
    "parentCode": "210000",
    "center": [
      122.06957,
      41.124484
    ],
    "province": "辽宁省"
  },
  {
    "code": "211200",
    "name": "铁岭市",
    "level": "city",
    "parentCode": "210000",
    "center": [
      123.844279,
      42.290585
    ],
    "province": "辽宁省"
  },
  {
    "code": "211300",
    "name": "朝阳市",
    "level": "city",
    "parentCode": "210000",
    "center": [
      120.451176,
      41.576758
    ],
    "province": "辽宁省"
  },
  {
    "code": "211400",
    "name": "葫芦岛市",
    "level": "city",
    "parentCode": "210000",
    "center": [
      120.856394,
      40.755572
    ],
    "province": "辽宁省"
  },
  {
    "code": "220100",
    "name": "长春市",
    "level": "city",
    "parentCode": "220000",
    "center": [
      125.3245,
      43.886841
    ],
    "province": "吉林省"
  },
  {
    "code": "220200",
    "name": "吉林市",
    "level": "city",
    "parentCode": "220000",
    "center": [
      126.55302,
      43.843577
    ],
    "province": "吉林省"
  },
  {
    "code": "220300",
    "name": "四平市",
    "level": "city",
    "parentCode": "220000",
    "center": [
      124.370785,
      43.170344
    ],
    "province": "吉林省"
  },
  {
    "code": "220400",
    "name": "辽源市",
    "level": "city",
    "parentCode": "220000",
    "center": [
      125.145349,
      42.902692
    ],
    "province": "吉林省"
  },
  {
    "code": "220500",
    "name": "通化市",
    "level": "city",
    "parentCode": "220000",
    "center": [
      125.936501,
      41.721177
    ],
    "province": "吉林省"
  },
  {
    "code": "220600",
    "name": "白山市",
    "level": "city",
    "parentCode": "220000",
    "center": [
      126.427839,
      41.942505
    ],
    "province": "吉林省"
  },
  {
    "code": "220700",
    "name": "松原市",
    "level": "city",
    "parentCode": "220000",
    "center": [
      124.823608,
      45.118243
    ],
    "province": "吉林省"
  },
  {
    "code": "220800",
    "name": "白城市",
    "level": "city",
    "parentCode": "220000",
    "center": [
      122.841114,
      45.619026
    ],
    "province": "吉林省"
  },
  {
    "code": "222400",
    "name": "延边朝鲜族自治州",
    "level": "city",
    "parentCode": "220000",
    "center": [
      129.513228,
      42.904823
    ],
    "province": "吉林省"
  },
  {
    "code": "230100",
    "name": "哈尔滨市",
    "level": "city",
    "parentCode": "230000",
    "center": [
      126.642464,
      45.756967
    ],
    "province": "黑龙江省"
  },
  {
    "code": "230200",
    "name": "齐齐哈尔市",
    "level": "city",
    "parentCode": "230000",
    "center": [
      123.95792,
      47.342081
    ],
    "province": "黑龙江省"
  },
  {
    "code": "230300",
    "name": "鸡西市",
    "level": "city",
    "parentCode": "230000",
    "center": [
      130.975966,
      45.300046
    ],
    "province": "黑龙江省"
  },
  {
    "code": "230400",
    "name": "鹤岗市",
    "level": "city",
    "parentCode": "230000",
    "center": [
      130.277487,
      47.332085
    ],
    "province": "黑龙江省"
  },
  {
    "code": "230500",
    "name": "双鸭山市",
    "level": "city",
    "parentCode": "230000",
    "center": [
      131.157304,
      46.643442
    ],
    "province": "黑龙江省"
  },
  {
    "code": "230600",
    "name": "大庆市",
    "level": "city",
    "parentCode": "230000",
    "center": [
      125.11272,
      46.590734
    ],
    "province": "黑龙江省"
  },
  {
    "code": "230700",
    "name": "伊春市",
    "level": "city",
    "parentCode": "230000",
    "center": [
      128.899396,
      47.724775
    ],
    "province": "黑龙江省"
  },
  {
    "code": "230800",
    "name": "佳木斯市",
    "level": "city",
    "parentCode": "230000",
    "center": [
      130.361634,
      46.809606
    ],
    "province": "黑龙江省"
  },
  {
    "code": "230900",
    "name": "七台河市",
    "level": "city",
    "parentCode": "230000",
    "center": [
      131.015584,
      45.771266
    ],
    "province": "黑龙江省"
  },
  {
    "code": "231000",
    "name": "牡丹江市",
    "level": "city",
    "parentCode": "230000",
    "center": [
      129.618602,
      44.582962
    ],
    "province": "黑龙江省"
  },
  {
    "code": "231100",
    "name": "黑河市",
    "level": "city",
    "parentCode": "230000",
    "center": [
      127.499023,
      50.249585
    ],
    "province": "黑龙江省"
  },
  {
    "code": "231200",
    "name": "绥化市",
    "level": "city",
    "parentCode": "230000",
    "center": [
      126.99293,
      46.637393
    ],
    "province": "黑龙江省"
  },
  {
    "code": "232700",
    "name": "大兴安岭地区",
    "level": "city",
    "parentCode": "230000",
    "center": [
      124.711526,
      52.335262
    ],
    "province": "黑龙江省"
  },
  {
    "code": "310101",
    "name": "黄浦区",
    "level": "county",
    "parentCode": "310000",
    "center": [
      121.490317,
      31.222771
    ],
    "province": "上海市"
  },
  {
    "code": "310104",
    "name": "徐汇区",
    "level": "county",
    "parentCode": "310000",
    "center": [
      121.43752,
      31.179973
    ],
    "province": "上海市"
  },
  {
    "code": "310105",
    "name": "长宁区",
    "level": "county",
    "parentCode": "310000",
    "center": [
      121.4222,
      31.218123
    ],
    "province": "上海市"
  },
  {
    "code": "310106",
    "name": "静安区",
    "level": "county",
    "parentCode": "310000",
    "center": [
      121.448224,
      31.229003
    ],
    "province": "上海市"
  },
  {
    "code": "310107",
    "name": "普陀区",
    "level": "county",
    "parentCode": "310000",
    "center": [
      121.392499,
      31.241701
    ],
    "province": "上海市"
  },
  {
    "code": "310109",
    "name": "虹口区",
    "level": "county",
    "parentCode": "310000",
    "center": [
      121.491832,
      31.26097
    ],
    "province": "上海市"
  },
  {
    "code": "310110",
    "name": "杨浦区",
    "level": "county",
    "parentCode": "310000",
    "center": [
      121.522797,
      31.270755
    ],
    "province": "上海市"
  },
  {
    "code": "310112",
    "name": "闵行区",
    "level": "county",
    "parentCode": "310000",
    "center": [
      121.375972,
      31.111658
    ],
    "province": "上海市"
  },
  {
    "code": "310113",
    "name": "宝山区",
    "level": "county",
    "parentCode": "310000",
    "center": [
      121.489934,
      31.398896
    ],
    "province": "上海市"
  },
  {
    "code": "310114",
    "name": "嘉定区",
    "level": "county",
    "parentCode": "310000",
    "center": [
      121.250333,
      31.383524
    ],
    "province": "上海市"
  },
  {
    "code": "310115",
    "name": "浦东新区",
    "level": "county",
    "parentCode": "310000",
    "center": [
      121.567706,
      31.245944
    ],
    "province": "上海市"
  },
  {
    "code": "310116",
    "name": "金山区",
    "level": "county",
    "parentCode": "310000",
    "center": [
      121.330736,
      30.724697
    ],
    "province": "上海市"
  },
  {
    "code": "310117",
    "name": "松江区",
    "level": "county",
    "parentCode": "310000",
    "center": [
      121.223543,
      31.03047
    ],
    "province": "上海市"
  },
  {
    "code": "310118",
    "name": "青浦区",
    "level": "county",
    "parentCode": "310000",
    "center": [
      121.113021,
      31.151209
    ],
    "province": "上海市"
  },
  {
    "code": "310120",
    "name": "奉贤区",
    "level": "county",
    "parentCode": "310000",
    "center": [
      121.458472,
      30.912345
    ],
    "province": "上海市"
  },
  {
    "code": "310151",
    "name": "崇明区",
    "level": "county",
    "parentCode": "310000",
    "center": [
      121.397516,
      31.626946
    ],
    "province": "上海市"
  },
  {
    "code": "320100",
    "name": "南京市",
    "level": "city",
    "parentCode": "320000",
    "center": [
      118.767413,
      32.041544
    ],
    "province": "江苏省"
  },
  {
    "code": "320200",
    "name": "无锡市",
    "level": "city",
    "parentCode": "320000",
    "center": [
      120.301663,
      31.574729
    ],
    "province": "江苏省"
  },
  {
    "code": "320300",
    "name": "徐州市",
    "level": "city",
    "parentCode": "320000",
    "center": [
      117.184811,
      34.261792
    ],
    "province": "江苏省"
  },
  {
    "code": "320400",
    "name": "常州市",
    "level": "city",
    "parentCode": "320000",
    "center": [
      119.946973,
      31.772752
    ],
    "province": "江苏省"
  },
  {
    "code": "320500",
    "name": "苏州市",
    "level": "city",
    "parentCode": "320000",
    "center": [
      120.619585,
      31.299379
    ],
    "province": "江苏省"
  },
  {
    "code": "320600",
    "name": "南通市",
    "level": "city",
    "parentCode": "320000",
    "center": [
      120.864608,
      32.016212
    ],
    "province": "江苏省"
  },
  {
    "code": "320700",
    "name": "连云港市",
    "level": "city",
    "parentCode": "320000",
    "center": [
      119.178821,
      34.600018
    ],
    "province": "江苏省"
  },
  {
    "code": "320800",
    "name": "淮安市",
    "level": "city",
    "parentCode": "320000",
    "center": [
      119.021265,
      33.597506
    ],
    "province": "江苏省"
  },
  {
    "code": "320900",
    "name": "盐城市",
    "level": "city",
    "parentCode": "320000",
    "center": [
      120.139998,
      33.377631
    ],
    "province": "江苏省"
  },
  {
    "code": "321000",
    "name": "扬州市",
    "level": "city",
    "parentCode": "320000",
    "center": [
      119.421003,
      32.393159
    ],
    "province": "江苏省"
  },
  {
    "code": "321100",
    "name": "镇江市",
    "level": "city",
    "parentCode": "320000",
    "center": [
      119.452753,
      32.204402
    ],
    "province": "江苏省"
  },
  {
    "code": "321200",
    "name": "泰州市",
    "level": "city",
    "parentCode": "320000",
    "center": [
      119.915176,
      32.484882
    ],
    "province": "江苏省"
  },
  {
    "code": "321300",
    "name": "宿迁市",
    "level": "city",
    "parentCode": "320000",
    "center": [
      118.275162,
      33.963008
    ],
    "province": "江苏省"
  },
  {
    "code": "330100",
    "name": "杭州市",
    "level": "city",
    "parentCode": "330000",
    "center": [
      120.153576,
      30.287459
    ],
    "province": "浙江省"
  },
  {
    "code": "330200",
    "name": "宁波市",
    "level": "city",
    "parentCode": "330000",
    "center": [
      121.549792,
      29.868388
    ],
    "province": "浙江省"
  },
  {
    "code": "330300",
    "name": "温州市",
    "level": "city",
    "parentCode": "330000",
    "center": [
      120.672111,
      28.000575
    ],
    "province": "浙江省"
  },
  {
    "code": "330400",
    "name": "嘉兴市",
    "level": "city",
    "parentCode": "330000",
    "center": [
      120.750865,
      30.762653
    ],
    "province": "浙江省"
  },
  {
    "code": "330500",
    "name": "湖州市",
    "level": "city",
    "parentCode": "330000",
    "center": [
      120.102398,
      30.867198
    ],
    "province": "浙江省"
  },
  {
    "code": "330600",
    "name": "绍兴市",
    "level": "city",
    "parentCode": "330000",
    "center": [
      120.582112,
      29.997117
    ],
    "province": "浙江省"
  },
  {
    "code": "330700",
    "name": "金华市",
    "level": "city",
    "parentCode": "330000",
    "center": [
      119.649506,
      29.089524
    ],
    "province": "浙江省"
  },
  {
    "code": "330800",
    "name": "衢州市",
    "level": "city",
    "parentCode": "330000",
    "center": [
      118.87263,
      28.941708
    ],
    "province": "浙江省"
  },
  {
    "code": "330900",
    "name": "舟山市",
    "level": "city",
    "parentCode": "330000",
    "center": [
      122.106863,
      30.016028
    ],
    "province": "浙江省"
  },
  {
    "code": "331000",
    "name": "台州市",
    "level": "city",
    "parentCode": "330000",
    "center": [
      121.428599,
      28.661378
    ],
    "province": "浙江省"
  },
  {
    "code": "331100",
    "name": "丽水市",
    "level": "city",
    "parentCode": "330000",
    "center": [
      119.921786,
      28.451993
    ],
    "province": "浙江省"
  },
  {
    "code": "340100",
    "name": "合肥市",
    "level": "city",
    "parentCode": "340000",
    "center": [
      117.283042,
      31.86119
    ],
    "province": "安徽省"
  },
  {
    "code": "340200",
    "name": "芜湖市",
    "level": "city",
    "parentCode": "340000",
    "center": [
      118.376451,
      31.326319
    ],
    "province": "安徽省"
  },
  {
    "code": "340300",
    "name": "蚌埠市",
    "level": "city",
    "parentCode": "340000",
    "center": [
      117.363228,
      32.939667
    ],
    "province": "安徽省"
  },
  {
    "code": "340400",
    "name": "淮南市",
    "level": "city",
    "parentCode": "340000",
    "center": [
      117.018329,
      32.647574
    ],
    "province": "安徽省"
  },
  {
    "code": "340500",
    "name": "马鞍山市",
    "level": "city",
    "parentCode": "340000",
    "center": [
      118.507906,
      31.689362
    ],
    "province": "安徽省"
  },
  {
    "code": "340600",
    "name": "淮北市",
    "level": "city",
    "parentCode": "340000",
    "center": [
      116.794664,
      33.971707
    ],
    "province": "安徽省"
  },
  {
    "code": "340700",
    "name": "铜陵市",
    "level": "city",
    "parentCode": "340000",
    "center": [
      117.816576,
      30.929935
    ],
    "province": "安徽省"
  },
  {
    "code": "340800",
    "name": "安庆市",
    "level": "city",
    "parentCode": "340000",
    "center": [
      117.043551,
      30.50883
    ],
    "province": "安徽省"
  },
  {
    "code": "341000",
    "name": "黄山市",
    "level": "city",
    "parentCode": "340000",
    "center": [
      118.317325,
      29.709239
    ],
    "province": "安徽省"
  },
  {
    "code": "341100",
    "name": "滁州市",
    "level": "city",
    "parentCode": "340000",
    "center": [
      118.316264,
      32.303627
    ],
    "province": "安徽省"
  },
  {
    "code": "341200",
    "name": "阜阳市",
    "level": "city",
    "parentCode": "340000",
    "center": [
      115.819729,
      32.896969
    ],
    "province": "安徽省"
  },
  {
    "code": "341300",
    "name": "宿州市",
    "level": "city",
    "parentCode": "340000",
    "center": [
      116.984084,
      33.633891
    ],
    "province": "安徽省"
  },
  {
    "code": "341500",
    "name": "六安市",
    "level": "city",
    "parentCode": "340000",
    "center": [
      116.507676,
      31.752889
    ],
    "province": "安徽省"
  },
  {
    "code": "341600",
    "name": "亳州市",
    "level": "city",
    "parentCode": "340000",
    "center": [
      115.782939,
      33.869338
    ],
    "province": "安徽省"
  },
  {
    "code": "341700",
    "name": "池州市",
    "level": "city",
    "parentCode": "340000",
    "center": [
      117.489157,
      30.656037
    ],
    "province": "安徽省"
  },
  {
    "code": "341800",
    "name": "宣城市",
    "level": "city",
    "parentCode": "340000",
    "center": [
      118.757995,
      30.945667
    ],
    "province": "安徽省"
  },
  {
    "code": "350100",
    "name": "福州市",
    "level": "city",
    "parentCode": "350000",
    "center": [
      119.306239,
      26.075302
    ],
    "province": "福建省"
  },
  {
    "code": "350200",
    "name": "厦门市",
    "level": "city",
    "parentCode": "350000",
    "center": [
      118.11022,
      24.490474
    ],
    "province": "福建省"
  },
  {
    "code": "350300",
    "name": "莆田市",
    "level": "city",
    "parentCode": "350000",
    "center": [
      119.007558,
      25.431011
    ],
    "province": "福建省"
  },
  {
    "code": "350400",
    "name": "三明市",
    "level": "city",
    "parentCode": "350000",
    "center": [
      117.635001,
      26.265444
    ],
    "province": "福建省"
  },
  {
    "code": "350500",
    "name": "泉州市",
    "level": "city",
    "parentCode": "350000",
    "center": [
      118.589421,
      24.908853
    ],
    "province": "福建省"
  },
  {
    "code": "350600",
    "name": "漳州市",
    "level": "city",
    "parentCode": "350000",
    "center": [
      117.661801,
      24.510897
    ],
    "province": "福建省"
  },
  {
    "code": "350700",
    "name": "南平市",
    "level": "city",
    "parentCode": "350000",
    "center": [
      118.178459,
      26.635627
    ],
    "province": "福建省"
  },
  {
    "code": "350800",
    "name": "龙岩市",
    "level": "city",
    "parentCode": "350000",
    "center": [
      117.02978,
      25.091603
    ],
    "province": "福建省"
  },
  {
    "code": "350900",
    "name": "宁德市",
    "level": "city",
    "parentCode": "350000",
    "center": [
      119.527082,
      26.65924
    ],
    "province": "福建省"
  },
  {
    "code": "360100",
    "name": "南昌市",
    "level": "city",
    "parentCode": "360000",
    "center": [
      115.892151,
      28.676493
    ],
    "province": "江西省"
  },
  {
    "code": "360200",
    "name": "景德镇市",
    "level": "city",
    "parentCode": "360000",
    "center": [
      117.214664,
      29.29256
    ],
    "province": "江西省"
  },
  {
    "code": "360300",
    "name": "萍乡市",
    "level": "city",
    "parentCode": "360000",
    "center": [
      113.852186,
      27.622946
    ],
    "province": "江西省"
  },
  {
    "code": "360400",
    "name": "九江市",
    "level": "city",
    "parentCode": "360000",
    "center": [
      115.992811,
      29.712034
    ],
    "province": "江西省"
  },
  {
    "code": "360500",
    "name": "新余市",
    "level": "city",
    "parentCode": "360000",
    "center": [
      114.930835,
      27.810834
    ],
    "province": "江西省"
  },
  {
    "code": "360600",
    "name": "鹰潭市",
    "level": "city",
    "parentCode": "360000",
    "center": [
      117.033838,
      28.238638
    ],
    "province": "江西省"
  },
  {
    "code": "360700",
    "name": "赣州市",
    "level": "city",
    "parentCode": "360000",
    "center": [
      114.940278,
      25.85097
    ],
    "province": "江西省"
  },
  {
    "code": "360800",
    "name": "吉安市",
    "level": "city",
    "parentCode": "360000",
    "center": [
      114.986373,
      27.111699
    ],
    "province": "江西省"
  },
  {
    "code": "360900",
    "name": "宜春市",
    "level": "city",
    "parentCode": "360000",
    "center": [
      114.391136,
      27.8043
    ],
    "province": "江西省"
  },
  {
    "code": "361000",
    "name": "抚州市",
    "level": "city",
    "parentCode": "360000",
    "center": [
      116.358351,
      27.98385
    ],
    "province": "江西省"
  },
  {
    "code": "361100",
    "name": "上饶市",
    "level": "city",
    "parentCode": "360000",
    "center": [
      117.971185,
      28.44442
    ],
    "province": "江西省"
  },
  {
    "code": "370100",
    "name": "济南市",
    "level": "city",
    "parentCode": "370000",
    "center": [
      117.000923,
      36.675807
    ],
    "province": "山东省"
  },
  {
    "code": "370200",
    "name": "青岛市",
    "level": "city",
    "parentCode": "370000",
    "center": [
      120.355173,
      36.082982
    ],
    "province": "山东省"
  },
  {
    "code": "370300",
    "name": "淄博市",
    "level": "city",
    "parentCode": "370000",
    "center": [
      118.047648,
      36.814939
    ],
    "province": "山东省"
  },
  {
    "code": "370400",
    "name": "枣庄市",
    "level": "city",
    "parentCode": "370000",
    "center": [
      117.557964,
      34.856424
    ],
    "province": "山东省"
  },
  {
    "code": "370500",
    "name": "东营市",
    "level": "city",
    "parentCode": "370000",
    "center": [
      118.66471,
      37.434564
    ],
    "province": "山东省"
  },
  {
    "code": "370600",
    "name": "烟台市",
    "level": "city",
    "parentCode": "370000",
    "center": [
      121.391382,
      37.539297
    ],
    "province": "山东省"
  },
  {
    "code": "370700",
    "name": "潍坊市",
    "level": "city",
    "parentCode": "370000",
    "center": [
      119.107078,
      36.70925
    ],
    "province": "山东省"
  },
  {
    "code": "370800",
    "name": "济宁市",
    "level": "city",
    "parentCode": "370000",
    "center": [
      116.587245,
      35.415393
    ],
    "province": "山东省"
  },
  {
    "code": "370900",
    "name": "泰安市",
    "level": "city",
    "parentCode": "370000",
    "center": [
      117.129063,
      36.194968
    ],
    "province": "山东省"
  },
  {
    "code": "371000",
    "name": "威海市",
    "level": "city",
    "parentCode": "370000",
    "center": [
      122.116394,
      37.509691
    ],
    "province": "山东省"
  },
  {
    "code": "371100",
    "name": "日照市",
    "level": "city",
    "parentCode": "370000",
    "center": [
      119.461208,
      35.428588
    ],
    "province": "山东省"
  },
  {
    "code": "371300",
    "name": "临沂市",
    "level": "city",
    "parentCode": "370000",
    "center": [
      118.326443,
      35.065282
    ],
    "province": "山东省"
  },
  {
    "code": "371400",
    "name": "德州市",
    "level": "city",
    "parentCode": "370000",
    "center": [
      116.307428,
      37.453968
    ],
    "province": "山东省"
  },
  {
    "code": "371500",
    "name": "聊城市",
    "level": "city",
    "parentCode": "370000",
    "center": [
      115.980367,
      36.456013
    ],
    "province": "山东省"
  },
  {
    "code": "371600",
    "name": "滨州市",
    "level": "city",
    "parentCode": "370000",
    "center": [
      118.016974,
      37.383542
    ],
    "province": "山东省"
  },
  {
    "code": "371700",
    "name": "菏泽市",
    "level": "city",
    "parentCode": "370000",
    "center": [
      115.469381,
      35.246531
    ],
    "province": "山东省"
  },
  {
    "code": "410100",
    "name": "郑州市",
    "level": "city",
    "parentCode": "410000",
    "center": [
      113.665412,
      34.757975
    ],
    "province": "河南省"
  },
  {
    "code": "410200",
    "name": "开封市",
    "level": "city",
    "parentCode": "410000",
    "center": [
      114.341447,
      34.797049
    ],
    "province": "河南省"
  },
  {
    "code": "410300",
    "name": "洛阳市",
    "level": "city",
    "parentCode": "410000",
    "center": [
      112.434468,
      34.663041
    ],
    "province": "河南省"
  },
  {
    "code": "410400",
    "name": "平顶山市",
    "level": "city",
    "parentCode": "410000",
    "center": [
      113.307718,
      33.735241
    ],
    "province": "河南省"
  },
  {
    "code": "410500",
    "name": "安阳市",
    "level": "city",
    "parentCode": "410000",
    "center": [
      114.352482,
      36.103442
    ],
    "province": "河南省"
  },
  {
    "code": "410600",
    "name": "鹤壁市",
    "level": "city",
    "parentCode": "410000",
    "center": [
      114.295444,
      35.748236
    ],
    "province": "河南省"
  },
  {
    "code": "410700",
    "name": "新乡市",
    "level": "city",
    "parentCode": "410000",
    "center": [
      113.883991,
      35.302616
    ],
    "province": "河南省"
  },
  {
    "code": "410800",
    "name": "焦作市",
    "level": "city",
    "parentCode": "410000",
    "center": [
      113.238266,
      35.23904
    ],
    "province": "河南省"
  },
  {
    "code": "410900",
    "name": "濮阳市",
    "level": "city",
    "parentCode": "410000",
    "center": [
      115.041299,
      35.768234
    ],
    "province": "河南省"
  },
  {
    "code": "411000",
    "name": "许昌市",
    "level": "city",
    "parentCode": "410000",
    "center": [
      113.826063,
      34.022956
    ],
    "province": "河南省"
  },
  {
    "code": "411100",
    "name": "漯河市",
    "level": "city",
    "parentCode": "410000",
    "center": [
      114.026405,
      33.575855
    ],
    "province": "河南省"
  },
  {
    "code": "411200",
    "name": "三门峡市",
    "level": "city",
    "parentCode": "410000",
    "center": [
      111.194099,
      34.777338
    ],
    "province": "河南省"
  },
  {
    "code": "411300",
    "name": "南阳市",
    "level": "city",
    "parentCode": "410000",
    "center": [
      112.540918,
      32.999082
    ],
    "province": "河南省"
  },
  {
    "code": "411400",
    "name": "商丘市",
    "level": "city",
    "parentCode": "410000",
    "center": [
      115.650497,
      34.437054
    ],
    "province": "河南省"
  },
  {
    "code": "411500",
    "name": "信阳市",
    "level": "city",
    "parentCode": "410000",
    "center": [
      114.075031,
      32.123274
    ],
    "province": "河南省"
  },
  {
    "code": "411600",
    "name": "周口市",
    "level": "city",
    "parentCode": "410000",
    "center": [
      114.649653,
      33.620357
    ],
    "province": "河南省"
  },
  {
    "code": "411700",
    "name": "驻马店市",
    "level": "city",
    "parentCode": "410000",
    "center": [
      114.024736,
      32.980169
    ],
    "province": "河南省"
  },
  {
    "code": "419001",
    "name": "济源市",
    "level": "city",
    "parentCode": "410000",
    "center": [
      112.590047,
      35.090378
    ],
    "province": "河南省"
  },
  {
    "code": "420100",
    "name": "武汉市",
    "level": "city",
    "parentCode": "420000",
    "center": [
      114.298572,
      30.584355
    ],
    "province": "湖北省"
  },
  {
    "code": "420200",
    "name": "黄石市",
    "level": "city",
    "parentCode": "420000",
    "center": [
      115.077048,
      30.220074
    ],
    "province": "湖北省"
  },
  {
    "code": "420300",
    "name": "十堰市",
    "level": "city",
    "parentCode": "420000",
    "center": [
      110.787916,
      32.646907
    ],
    "province": "湖北省"
  },
  {
    "code": "420500",
    "name": "宜昌市",
    "level": "city",
    "parentCode": "420000",
    "center": [
      111.290843,
      30.702636
    ],
    "province": "湖北省"
  },
  {
    "code": "420600",
    "name": "襄阳市",
    "level": "city",
    "parentCode": "420000",
    "center": [
      112.144146,
      32.042426
    ],
    "province": "湖北省"
  },
  {
    "code": "420700",
    "name": "鄂州市",
    "level": "city",
    "parentCode": "420000",
    "center": [
      114.890593,
      30.396536
    ],
    "province": "湖北省"
  },
  {
    "code": "420800",
    "name": "荆门市",
    "level": "city",
    "parentCode": "420000",
    "center": [
      112.204251,
      31.03542
    ],
    "province": "湖北省"
  },
  {
    "code": "420900",
    "name": "孝感市",
    "level": "city",
    "parentCode": "420000",
    "center": [
      113.926655,
      30.926423
    ],
    "province": "湖北省"
  },
  {
    "code": "421000",
    "name": "荆州市",
    "level": "city",
    "parentCode": "420000",
    "center": [
      112.23813,
      30.326857
    ],
    "province": "湖北省"
  },
  {
    "code": "421100",
    "name": "黄冈市",
    "level": "city",
    "parentCode": "420000",
    "center": [
      114.879365,
      30.447711
    ],
    "province": "湖北省"
  },
  {
    "code": "421200",
    "name": "咸宁市",
    "level": "city",
    "parentCode": "420000",
    "center": [
      114.328963,
      29.832798
    ],
    "province": "湖北省"
  },
  {
    "code": "421300",
    "name": "随州市",
    "level": "city",
    "parentCode": "420000",
    "center": [
      113.37377,
      31.717497
    ],
    "province": "湖北省"
  },
  {
    "code": "422800",
    "name": "恩施土家族苗族自治州",
    "level": "city",
    "parentCode": "420000",
    "center": [
      109.48699,
      30.283114
    ],
    "province": "湖北省"
  },
  {
    "code": "429004",
    "name": "仙桃市",
    "level": "city",
    "parentCode": "420000",
    "center": [
      113.453974,
      30.364953
    ],
    "province": "湖北省"
  },
  {
    "code": "429005",
    "name": "潜江市",
    "level": "city",
    "parentCode": "420000",
    "center": [
      112.896866,
      30.421215
    ],
    "province": "湖北省"
  },
  {
    "code": "429006",
    "name": "天门市",
    "level": "city",
    "parentCode": "420000",
    "center": [
      113.165862,
      30.653061
    ],
    "province": "湖北省"
  },
  {
    "code": "429021",
    "name": "神农架林区",
    "level": "city",
    "parentCode": "420000",
    "center": [
      110.671525,
      31.744449
    ],
    "province": "湖北省"
  },
  {
    "code": "430100",
    "name": "长沙市",
    "level": "city",
    "parentCode": "430000",
    "center": [
      112.982279,
      28.19409
    ],
    "province": "湖南省"
  },
  {
    "code": "430200",
    "name": "株洲市",
    "level": "city",
    "parentCode": "430000",
    "center": [
      113.151737,
      27.835806
    ],
    "province": "湖南省"
  },
  {
    "code": "430300",
    "name": "湘潭市",
    "level": "city",
    "parentCode": "430000",
    "center": [
      112.944052,
      27.82973
    ],
    "province": "湖南省"
  },
  {
    "code": "430400",
    "name": "衡阳市",
    "level": "city",
    "parentCode": "430000",
    "center": [
      112.607693,
      26.900358
    ],
    "province": "湖南省"
  },
  {
    "code": "430500",
    "name": "邵阳市",
    "level": "city",
    "parentCode": "430000",
    "center": [
      111.46923,
      27.237842
    ],
    "province": "湖南省"
  },
  {
    "code": "430600",
    "name": "岳阳市",
    "level": "city",
    "parentCode": "430000",
    "center": [
      113.132855,
      29.37029
    ],
    "province": "湖南省"
  },
  {
    "code": "430700",
    "name": "常德市",
    "level": "city",
    "parentCode": "430000",
    "center": [
      111.691347,
      29.040225
    ],
    "province": "湖南省"
  },
  {
    "code": "430800",
    "name": "张家界市",
    "level": "city",
    "parentCode": "430000",
    "center": [
      110.479921,
      29.127401
    ],
    "province": "湖南省"
  },
  {
    "code": "430900",
    "name": "益阳市",
    "level": "city",
    "parentCode": "430000",
    "center": [
      112.355042,
      28.570066
    ],
    "province": "湖南省"
  },
  {
    "code": "431000",
    "name": "郴州市",
    "level": "city",
    "parentCode": "430000",
    "center": [
      113.032067,
      25.793589
    ],
    "province": "湖南省"
  },
  {
    "code": "431100",
    "name": "永州市",
    "level": "city",
    "parentCode": "430000",
    "center": [
      111.608019,
      26.434516
    ],
    "province": "湖南省"
  },
  {
    "code": "431200",
    "name": "怀化市",
    "level": "city",
    "parentCode": "430000",
    "center": [
      109.97824,
      27.550082
    ],
    "province": "湖南省"
  },
  {
    "code": "431300",
    "name": "娄底市",
    "level": "city",
    "parentCode": "430000",
    "center": [
      112.008497,
      27.728136
    ],
    "province": "湖南省"
  },
  {
    "code": "433100",
    "name": "湘西土家族苗族自治州",
    "level": "city",
    "parentCode": "430000",
    "center": [
      109.739735,
      28.314296
    ],
    "province": "湖南省"
  },
  {
    "code": "440100",
    "name": "广州市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      113.280637,
      23.125178
    ],
    "province": "广东省"
  },
  {
    "code": "440200",
    "name": "韶关市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      113.591544,
      24.801322
    ],
    "province": "广东省"
  },
  {
    "code": "440300",
    "name": "深圳市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      114.085947,
      22.547
    ],
    "province": "广东省"
  },
  {
    "code": "440400",
    "name": "珠海市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      113.553986,
      22.224979
    ],
    "province": "广东省"
  },
  {
    "code": "440500",
    "name": "汕头市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      116.708463,
      23.37102
    ],
    "province": "广东省"
  },
  {
    "code": "440600",
    "name": "佛山市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      113.122717,
      23.028762
    ],
    "province": "广东省"
  },
  {
    "code": "440700",
    "name": "江门市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      113.094942,
      22.590431
    ],
    "province": "广东省"
  },
  {
    "code": "440800",
    "name": "湛江市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      110.364977,
      21.274898
    ],
    "province": "广东省"
  },
  {
    "code": "440900",
    "name": "茂名市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      110.919229,
      21.659751
    ],
    "province": "广东省"
  },
  {
    "code": "441200",
    "name": "肇庆市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      112.472529,
      23.051546
    ],
    "province": "广东省"
  },
  {
    "code": "441300",
    "name": "惠州市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      114.412599,
      23.079404
    ],
    "province": "广东省"
  },
  {
    "code": "441400",
    "name": "梅州市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      116.117582,
      24.299112
    ],
    "province": "广东省"
  },
  {
    "code": "441500",
    "name": "汕尾市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      115.364238,
      22.774485
    ],
    "province": "广东省"
  },
  {
    "code": "441600",
    "name": "河源市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      114.697802,
      23.746266
    ],
    "province": "广东省"
  },
  {
    "code": "441700",
    "name": "阳江市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      111.975107,
      21.859222
    ],
    "province": "广东省"
  },
  {
    "code": "441800",
    "name": "清远市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      113.051227,
      23.685022
    ],
    "province": "广东省"
  },
  {
    "code": "441900",
    "name": "东莞市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      113.746262,
      23.046237
    ],
    "province": "广东省"
  },
  {
    "code": "442000",
    "name": "中山市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      113.382391,
      22.521113
    ],
    "province": "广东省"
  },
  {
    "code": "445100",
    "name": "潮州市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      116.632301,
      23.661701
    ],
    "province": "广东省"
  },
  {
    "code": "445200",
    "name": "揭阳市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      116.355733,
      23.543778
    ],
    "province": "广东省"
  },
  {
    "code": "445300",
    "name": "云浮市",
    "level": "city",
    "parentCode": "440000",
    "center": [
      112.044439,
      22.929801
    ],
    "province": "广东省"
  },
  {
    "code": "450100",
    "name": "南宁市",
    "level": "city",
    "parentCode": "450000",
    "center": [
      108.320004,
      22.82402
    ],
    "province": "广西壮族自治区"
  },
  {
    "code": "450200",
    "name": "柳州市",
    "level": "city",
    "parentCode": "450000",
    "center": [
      109.411703,
      24.314617
    ],
    "province": "广西壮族自治区"
  },
  {
    "code": "450300",
    "name": "桂林市",
    "level": "city",
    "parentCode": "450000",
    "center": [
      110.299121,
      25.274215
    ],
    "province": "广西壮族自治区"
  },
  {
    "code": "450400",
    "name": "梧州市",
    "level": "city",
    "parentCode": "450000",
    "center": [
      111.297604,
      23.474803
    ],
    "province": "广西壮族自治区"
  },
  {
    "code": "450500",
    "name": "北海市",
    "level": "city",
    "parentCode": "450000",
    "center": [
      109.119254,
      21.473343
    ],
    "province": "广西壮族自治区"
  },
  {
    "code": "450600",
    "name": "防城港市",
    "level": "city",
    "parentCode": "450000",
    "center": [
      108.345478,
      21.614631
    ],
    "province": "广西壮族自治区"
  },
  {
    "code": "450700",
    "name": "钦州市",
    "level": "city",
    "parentCode": "450000",
    "center": [
      108.624175,
      21.967127
    ],
    "province": "广西壮族自治区"
  },
  {
    "code": "450800",
    "name": "贵港市",
    "level": "city",
    "parentCode": "450000",
    "center": [
      109.602146,
      23.0936
    ],
    "province": "广西壮族自治区"
  },
  {
    "code": "450900",
    "name": "玉林市",
    "level": "city",
    "parentCode": "450000",
    "center": [
      110.154393,
      22.63136
    ],
    "province": "广西壮族自治区"
  },
  {
    "code": "451000",
    "name": "百色市",
    "level": "city",
    "parentCode": "450000",
    "center": [
      106.616285,
      23.897742
    ],
    "province": "广西壮族自治区"
  },
  {
    "code": "451100",
    "name": "贺州市",
    "level": "city",
    "parentCode": "450000",
    "center": [
      111.552056,
      24.414141
    ],
    "province": "广西壮族自治区"
  },
  {
    "code": "451200",
    "name": "河池市",
    "level": "city",
    "parentCode": "450000",
    "center": [
      108.062105,
      24.695899
    ],
    "province": "广西壮族自治区"
  },
  {
    "code": "451300",
    "name": "来宾市",
    "level": "city",
    "parentCode": "450000",
    "center": [
      109.229772,
      23.733766
    ],
    "province": "广西壮族自治区"
  },
  {
    "code": "451400",
    "name": "崇左市",
    "level": "city",
    "parentCode": "450000",
    "center": [
      107.353926,
      22.404108
    ],
    "province": "广西壮族自治区"
  },
  {
    "code": "460100",
    "name": "海口市",
    "level": "city",
    "parentCode": "460000",
    "center": [
      110.33119,
      20.031971
    ],
    "province": "海南省"
  },
  {
    "code": "460200",
    "name": "三亚市",
    "level": "city",
    "parentCode": "460000",
    "center": [
      109.508268,
      18.247872
    ],
    "province": "海南省"
  },
  {
    "code": "460300",
    "name": "三沙市",
    "level": "city",
    "parentCode": "460000",
    "center": [
      112.34882,
      16.831039
    ],
    "province": "海南省"
  },
  {
    "code": "460400",
    "name": "儋州市",
    "level": "city",
    "parentCode": "460000",
    "center": [
      109.576782,
      19.517486
    ],
    "province": "海南省"
  },
  {
    "code": "469001",
    "name": "五指山市",
    "level": "city",
    "parentCode": "460000",
    "center": [
      109.516662,
      18.776921
    ],
    "province": "海南省"
  },
  {
    "code": "469002",
    "name": "琼海市",
    "level": "city",
    "parentCode": "460000",
    "center": [
      110.466785,
      19.246011
    ],
    "province": "海南省"
  },
  {
    "code": "469005",
    "name": "文昌市",
    "level": "city",
    "parentCode": "460000",
    "center": [
      110.753975,
      19.612986
    ],
    "province": "海南省"
  },
  {
    "code": "469006",
    "name": "万宁市",
    "level": "city",
    "parentCode": "460000",
    "center": [
      110.388793,
      18.796216
    ],
    "province": "海南省"
  },
  {
    "code": "469007",
    "name": "东方市",
    "level": "city",
    "parentCode": "460000",
    "center": [
      108.653789,
      19.10198
    ],
    "province": "海南省"
  },
  {
    "code": "469021",
    "name": "定安县",
    "level": "city",
    "parentCode": "460000",
    "center": [
      110.349235,
      19.684966
    ],
    "province": "海南省"
  },
  {
    "code": "469022",
    "name": "屯昌县",
    "level": "city",
    "parentCode": "460000",
    "center": [
      110.102773,
      19.362916
    ],
    "province": "海南省"
  },
  {
    "code": "469023",
    "name": "澄迈县",
    "level": "city",
    "parentCode": "460000",
    "center": [
      110.007147,
      19.737095
    ],
    "province": "海南省"
  },
  {
    "code": "469024",
    "name": "临高县",
    "level": "city",
    "parentCode": "460000",
    "center": [
      109.687697,
      19.908293
    ],
    "province": "海南省"
  },
  {
    "code": "469025",
    "name": "白沙黎族自治县",
    "level": "city",
    "parentCode": "460000",
    "center": [
      109.452606,
      19.224584
    ],
    "province": "海南省"
  },
  {
    "code": "469026",
    "name": "昌江黎族自治县",
    "level": "city",
    "parentCode": "460000",
    "center": [
      109.053351,
      19.260968
    ],
    "province": "海南省"
  },
  {
    "code": "469027",
    "name": "乐东黎族自治县",
    "level": "city",
    "parentCode": "460000",
    "center": [
      109.175444,
      18.74758
    ],
    "province": "海南省"
  },
  {
    "code": "469028",
    "name": "陵水黎族自治县",
    "level": "city",
    "parentCode": "460000",
    "center": [
      110.037218,
      18.505006
    ],
    "province": "海南省"
  },
  {
    "code": "469029",
    "name": "保亭黎族苗族自治县",
    "level": "city",
    "parentCode": "460000",
    "center": [
      109.70245,
      18.636371
    ],
    "province": "海南省"
  },
  {
    "code": "469030",
    "name": "琼中黎族苗族自治县",
    "level": "city",
    "parentCode": "460000",
    "center": [
      109.839996,
      19.03557
    ],
    "province": "海南省"
  },
  {
    "code": "500101",
    "name": "万州区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      108.380246,
      30.807807
    ],
    "province": "重庆市"
  },
  {
    "code": "500102",
    "name": "涪陵区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      107.394905,
      29.703652
    ],
    "province": "重庆市"
  },
  {
    "code": "500103",
    "name": "渝中区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      106.56288,
      29.556742
    ],
    "province": "重庆市"
  },
  {
    "code": "500104",
    "name": "大渡口区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      106.48613,
      29.481002
    ],
    "province": "重庆市"
  },
  {
    "code": "500105",
    "name": "江北区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      106.532844,
      29.575352
    ],
    "province": "重庆市"
  },
  {
    "code": "500106",
    "name": "沙坪坝区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      106.4542,
      29.541224
    ],
    "province": "重庆市"
  },
  {
    "code": "500107",
    "name": "九龙坡区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      106.480989,
      29.523492
    ],
    "province": "重庆市"
  },
  {
    "code": "500108",
    "name": "南岸区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      106.560813,
      29.523992
    ],
    "province": "重庆市"
  },
  {
    "code": "500109",
    "name": "北碚区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      106.437868,
      29.82543
    ],
    "province": "重庆市"
  },
  {
    "code": "500110",
    "name": "綦江区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      106.651417,
      29.028091
    ],
    "province": "重庆市"
  },
  {
    "code": "500111",
    "name": "大足区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      105.715319,
      29.700498
    ],
    "province": "重庆市"
  },
  {
    "code": "500112",
    "name": "渝北区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      106.512851,
      29.601451
    ],
    "province": "重庆市"
  },
  {
    "code": "500113",
    "name": "巴南区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      106.519423,
      29.381919
    ],
    "province": "重庆市"
  },
  {
    "code": "500114",
    "name": "黔江区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      108.782577,
      29.527548
    ],
    "province": "重庆市"
  },
  {
    "code": "500115",
    "name": "长寿区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      107.074854,
      29.833671
    ],
    "province": "重庆市"
  },
  {
    "code": "500116",
    "name": "江津区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      106.253156,
      29.283387
    ],
    "province": "重庆市"
  },
  {
    "code": "500117",
    "name": "合川区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      106.265554,
      29.990993
    ],
    "province": "重庆市"
  },
  {
    "code": "500118",
    "name": "永川区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      105.894714,
      29.348748
    ],
    "province": "重庆市"
  },
  {
    "code": "500119",
    "name": "南川区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      107.098153,
      29.156646
    ],
    "province": "重庆市"
  },
  {
    "code": "500120",
    "name": "璧山区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      106.231126,
      29.593581
    ],
    "province": "重庆市"
  },
  {
    "code": "500151",
    "name": "铜梁区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      106.054948,
      29.839944
    ],
    "province": "重庆市"
  },
  {
    "code": "500152",
    "name": "潼南区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      105.841818,
      30.189554
    ],
    "province": "重庆市"
  },
  {
    "code": "500153",
    "name": "荣昌区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      105.594061,
      29.403627
    ],
    "province": "重庆市"
  },
  {
    "code": "500154",
    "name": "开州区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      108.413317,
      31.167735
    ],
    "province": "重庆市"
  },
  {
    "code": "500155",
    "name": "梁平区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      107.800034,
      30.672168
    ],
    "province": "重庆市"
  },
  {
    "code": "500156",
    "name": "武隆区",
    "level": "county",
    "parentCode": "500000",
    "center": [
      107.75655,
      29.32376
    ],
    "province": "重庆市"
  },
  {
    "code": "500229",
    "name": "城口县",
    "level": "county",
    "parentCode": "500000",
    "center": [
      108.6649,
      31.946293
    ],
    "province": "重庆市"
  },
  {
    "code": "500230",
    "name": "丰都县",
    "level": "county",
    "parentCode": "500000",
    "center": [
      107.73248,
      29.866424
    ],
    "province": "重庆市"
  },
  {
    "code": "500231",
    "name": "垫江县",
    "level": "county",
    "parentCode": "500000",
    "center": [
      107.348692,
      30.330012
    ],
    "province": "重庆市"
  },
  {
    "code": "500233",
    "name": "忠县",
    "level": "county",
    "parentCode": "500000",
    "center": [
      108.037518,
      30.291537
    ],
    "province": "重庆市"
  },
  {
    "code": "500235",
    "name": "云阳县",
    "level": "county",
    "parentCode": "500000",
    "center": [
      108.697698,
      30.930529
    ],
    "province": "重庆市"
  },
  {
    "code": "500236",
    "name": "奉节县",
    "level": "county",
    "parentCode": "500000",
    "center": [
      109.465774,
      31.019967
    ],
    "province": "重庆市"
  },
  {
    "code": "500237",
    "name": "巫山县",
    "level": "county",
    "parentCode": "500000",
    "center": [
      109.878928,
      31.074843
    ],
    "province": "重庆市"
  },
  {
    "code": "500238",
    "name": "巫溪县",
    "level": "county",
    "parentCode": "500000",
    "center": [
      109.628912,
      31.3966
    ],
    "province": "重庆市"
  },
  {
    "code": "500240",
    "name": "石柱土家族自治县",
    "level": "county",
    "parentCode": "500000",
    "center": [
      108.112448,
      29.99853
    ],
    "province": "重庆市"
  },
  {
    "code": "500241",
    "name": "秀山土家族苗族自治县",
    "level": "county",
    "parentCode": "500000",
    "center": [
      108.996043,
      28.444772
    ],
    "province": "重庆市"
  },
  {
    "code": "500242",
    "name": "酉阳土家族苗族自治县",
    "level": "county",
    "parentCode": "500000",
    "center": [
      108.767201,
      28.839828
    ],
    "province": "重庆市"
  },
  {
    "code": "500243",
    "name": "彭水苗族土家族自治县",
    "level": "county",
    "parentCode": "500000",
    "center": [
      108.166551,
      29.293856
    ],
    "province": "重庆市"
  },
  {
    "code": "510100",
    "name": "成都市",
    "level": "city",
    "parentCode": "510000",
    "center": [
      104.065735,
      30.659462
    ],
    "province": "四川省"
  },
  {
    "code": "510300",
    "name": "自贡市",
    "level": "city",
    "parentCode": "510000",
    "center": [
      104.773447,
      29.352765
    ],
    "province": "四川省"
  },
  {
    "code": "510400",
    "name": "攀枝花市",
    "level": "city",
    "parentCode": "510000",
    "center": [
      101.716007,
      26.580446
    ],
    "province": "四川省"
  },
  {
    "code": "510500",
    "name": "泸州市",
    "level": "city",
    "parentCode": "510000",
    "center": [
      105.443348,
      28.889138
    ],
    "province": "四川省"
  },
  {
    "code": "510600",
    "name": "德阳市",
    "level": "city",
    "parentCode": "510000",
    "center": [
      104.398651,
      31.127991
    ],
    "province": "四川省"
  },
  {
    "code": "510700",
    "name": "绵阳市",
    "level": "city",
    "parentCode": "510000",
    "center": [
      104.741722,
      31.46402
    ],
    "province": "四川省"
  },
  {
    "code": "510800",
    "name": "广元市",
    "level": "city",
    "parentCode": "510000",
    "center": [
      105.829757,
      32.433668
    ],
    "province": "四川省"
  },
  {
    "code": "510900",
    "name": "遂宁市",
    "level": "city",
    "parentCode": "510000",
    "center": [
      105.571331,
      30.513311
    ],
    "province": "四川省"
  },
  {
    "code": "511000",
    "name": "内江市",
    "level": "city",
    "parentCode": "510000",
    "center": [
      105.066138,
      29.58708
    ],
    "province": "四川省"
  },
  {
    "code": "511100",
    "name": "乐山市",
    "level": "city",
    "parentCode": "510000",
    "center": [
      103.761263,
      29.582024
    ],
    "province": "四川省"
  },
  {
    "code": "511300",
    "name": "南充市",
    "level": "city",
    "parentCode": "510000",
    "center": [
      106.082974,
      30.795281
    ],
    "province": "四川省"
  },
  {
    "code": "511400",
    "name": "眉山市",
    "level": "city",
    "parentCode": "510000",
    "center": [
      103.831788,
      30.048318
    ],
    "province": "四川省"
  },
  {
    "code": "511500",
    "name": "宜宾市",
    "level": "city",
    "parentCode": "510000",
    "center": [
      104.630825,
      28.760189
    ],
    "province": "四川省"
  },
  {
    "code": "511600",
    "name": "广安市",
    "level": "city",
    "parentCode": "510000",
    "center": [
      106.633369,
      30.456398
    ],
    "province": "四川省"
  },
  {
    "code": "511700",
    "name": "达州市",
    "level": "city",
    "parentCode": "510000",
    "center": [
      107.502262,
      31.209484
    ],
    "province": "四川省"
  },
  {
    "code": "511800",
    "name": "雅安市",
    "level": "city",
    "parentCode": "510000",
    "center": [
      103.001033,
      29.987722
    ],
    "province": "四川省"
  },
  {
    "code": "511900",
    "name": "巴中市",
    "level": "city",
    "parentCode": "510000",
    "center": [
      106.753669,
      31.858809
    ],
    "province": "四川省"
  },
  {
    "code": "512000",
    "name": "资阳市",
    "level": "city",
    "parentCode": "510000",
    "center": [
      104.641917,
      30.122211
    ],
    "province": "四川省"
  },
  {
    "code": "513200",
    "name": "阿坝藏族羌族自治州",
    "level": "city",
    "parentCode": "510000",
    "center": [
      102.221374,
      31.899792
    ],
    "province": "四川省"
  },
  {
    "code": "513300",
    "name": "甘孜藏族自治州",
    "level": "city",
    "parentCode": "510000",
    "center": [
      101.963815,
      30.050663
    ],
    "province": "四川省"
  },
  {
    "code": "513400",
    "name": "凉山彝族自治州",
    "level": "city",
    "parentCode": "510000",
    "center": [
      102.258746,
      27.886762
    ],
    "province": "四川省"
  },
  {
    "code": "520100",
    "name": "贵阳市",
    "level": "city",
    "parentCode": "520000",
    "center": [
      106.713478,
      26.578343
    ],
    "province": "贵州省"
  },
  {
    "code": "520200",
    "name": "六盘水市",
    "level": "city",
    "parentCode": "520000",
    "center": [
      104.846743,
      26.584643
    ],
    "province": "贵州省"
  },
  {
    "code": "520300",
    "name": "遵义市",
    "level": "city",
    "parentCode": "520000",
    "center": [
      106.937265,
      27.706626
    ],
    "province": "贵州省"
  },
  {
    "code": "520400",
    "name": "安顺市",
    "level": "city",
    "parentCode": "520000",
    "center": [
      105.932188,
      26.245544
    ],
    "province": "贵州省"
  },
  {
    "code": "520500",
    "name": "毕节市",
    "level": "city",
    "parentCode": "520000",
    "center": [
      105.28501,
      27.301693
    ],
    "province": "贵州省"
  },
  {
    "code": "520600",
    "name": "铜仁市",
    "level": "city",
    "parentCode": "520000",
    "center": [
      109.191555,
      27.718346
    ],
    "province": "贵州省"
  },
  {
    "code": "522300",
    "name": "黔西南布依族苗族自治州",
    "level": "city",
    "parentCode": "520000",
    "center": [
      104.897971,
      25.08812
    ],
    "province": "贵州省"
  },
  {
    "code": "522600",
    "name": "黔东南苗族侗族自治州",
    "level": "city",
    "parentCode": "520000",
    "center": [
      107.977488,
      26.583352
    ],
    "province": "贵州省"
  },
  {
    "code": "522700",
    "name": "黔南布依族苗族自治州",
    "level": "city",
    "parentCode": "520000",
    "center": [
      107.517156,
      26.258219
    ],
    "province": "贵州省"
  },
  {
    "code": "530100",
    "name": "昆明市",
    "level": "city",
    "parentCode": "530000",
    "center": [
      102.712251,
      25.040609
    ],
    "province": "云南省"
  },
  {
    "code": "530300",
    "name": "曲靖市",
    "level": "city",
    "parentCode": "530000",
    "center": [
      103.797851,
      25.501557
    ],
    "province": "云南省"
  },
  {
    "code": "530400",
    "name": "玉溪市",
    "level": "city",
    "parentCode": "530000",
    "center": [
      102.543907,
      24.350461
    ],
    "province": "云南省"
  },
  {
    "code": "530500",
    "name": "保山市",
    "level": "city",
    "parentCode": "530000",
    "center": [
      99.167133,
      25.111802
    ],
    "province": "云南省"
  },
  {
    "code": "530600",
    "name": "昭通市",
    "level": "city",
    "parentCode": "530000",
    "center": [
      103.717216,
      27.336999
    ],
    "province": "云南省"
  },
  {
    "code": "530700",
    "name": "丽江市",
    "level": "city",
    "parentCode": "530000",
    "center": [
      100.233026,
      26.872108
    ],
    "province": "云南省"
  },
  {
    "code": "530800",
    "name": "普洱市",
    "level": "city",
    "parentCode": "530000",
    "center": [
      100.972344,
      22.777321
    ],
    "province": "云南省"
  },
  {
    "code": "530900",
    "name": "临沧市",
    "level": "city",
    "parentCode": "530000",
    "center": [
      100.08697,
      23.886567
    ],
    "province": "云南省"
  },
  {
    "code": "532300",
    "name": "楚雄彝族自治州",
    "level": "city",
    "parentCode": "530000",
    "center": [
      101.546046,
      25.041988
    ],
    "province": "云南省"
  },
  {
    "code": "532500",
    "name": "红河哈尼族彝族自治州",
    "level": "city",
    "parentCode": "530000",
    "center": [
      103.384182,
      23.366775
    ],
    "province": "云南省"
  },
  {
    "code": "532600",
    "name": "文山壮族苗族自治州",
    "level": "city",
    "parentCode": "530000",
    "center": [
      104.24401,
      23.36951
    ],
    "province": "云南省"
  },
  {
    "code": "532800",
    "name": "西双版纳傣族自治州",
    "level": "city",
    "parentCode": "530000",
    "center": [
      100.797941,
      22.001724
    ],
    "province": "云南省"
  },
  {
    "code": "532900",
    "name": "大理白族自治州",
    "level": "city",
    "parentCode": "530000",
    "center": [
      100.225668,
      25.589449
    ],
    "province": "云南省"
  },
  {
    "code": "533100",
    "name": "德宏傣族景颇族自治州",
    "level": "city",
    "parentCode": "530000",
    "center": [
      98.578363,
      24.436694
    ],
    "province": "云南省"
  },
  {
    "code": "533300",
    "name": "怒江傈僳族自治州",
    "level": "city",
    "parentCode": "530000",
    "center": [
      98.854304,
      25.850949
    ],
    "province": "云南省"
  },
  {
    "code": "533400",
    "name": "迪庆藏族自治州",
    "level": "city",
    "parentCode": "530000",
    "center": [
      99.706463,
      27.826853
    ],
    "province": "云南省"
  },
  {
    "code": "540100",
    "name": "拉萨市",
    "level": "city",
    "parentCode": "540000",
    "center": [
      91.132212,
      29.660361
    ],
    "province": "西藏自治区"
  },
  {
    "code": "540200",
    "name": "日喀则市",
    "level": "city",
    "parentCode": "540000",
    "center": [
      88.885148,
      29.267519
    ],
    "province": "西藏自治区"
  },
  {
    "code": "540300",
    "name": "昌都市",
    "level": "city",
    "parentCode": "540000",
    "center": [
      97.178452,
      31.136875
    ],
    "province": "西藏自治区"
  },
  {
    "code": "540400",
    "name": "林芝市",
    "level": "city",
    "parentCode": "540000",
    "center": [
      94.362348,
      29.654693
    ],
    "province": "西藏自治区"
  },
  {
    "code": "540500",
    "name": "山南市",
    "level": "city",
    "parentCode": "540000",
    "center": [
      91.766529,
      29.236023
    ],
    "province": "西藏自治区"
  },
  {
    "code": "540600",
    "name": "那曲市",
    "level": "city",
    "parentCode": "540000",
    "center": [
      92.060214,
      31.476004
    ],
    "province": "西藏自治区"
  },
  {
    "code": "542500",
    "name": "阿里地区",
    "level": "city",
    "parentCode": "540000",
    "center": [
      80.105498,
      32.503187
    ],
    "province": "西藏自治区"
  },
  {
    "code": "610100",
    "name": "西安市",
    "level": "city",
    "parentCode": "610000",
    "center": [
      108.948024,
      34.263161
    ],
    "province": "陕西省"
  },
  {
    "code": "610200",
    "name": "铜川市",
    "level": "city",
    "parentCode": "610000",
    "center": [
      108.979608,
      34.916582
    ],
    "province": "陕西省"
  },
  {
    "code": "610300",
    "name": "宝鸡市",
    "level": "city",
    "parentCode": "610000",
    "center": [
      107.14487,
      34.369315
    ],
    "province": "陕西省"
  },
  {
    "code": "610400",
    "name": "咸阳市",
    "level": "city",
    "parentCode": "610000",
    "center": [
      108.705117,
      34.333439
    ],
    "province": "陕西省"
  },
  {
    "code": "610500",
    "name": "渭南市",
    "level": "city",
    "parentCode": "610000",
    "center": [
      109.502882,
      34.499381
    ],
    "province": "陕西省"
  },
  {
    "code": "610600",
    "name": "延安市",
    "level": "city",
    "parentCode": "610000",
    "center": [
      109.49081,
      36.596537
    ],
    "province": "陕西省"
  },
  {
    "code": "610700",
    "name": "汉中市",
    "level": "city",
    "parentCode": "610000",
    "center": [
      107.028621,
      33.077668
    ],
    "province": "陕西省"
  },
  {
    "code": "610800",
    "name": "榆林市",
    "level": "city",
    "parentCode": "610000",
    "center": [
      109.741193,
      38.290162
    ],
    "province": "陕西省"
  },
  {
    "code": "610900",
    "name": "安康市",
    "level": "city",
    "parentCode": "610000",
    "center": [
      109.029273,
      32.6903
    ],
    "province": "陕西省"
  },
  {
    "code": "611000",
    "name": "商洛市",
    "level": "city",
    "parentCode": "610000",
    "center": [
      109.939776,
      33.868319
    ],
    "province": "陕西省"
  },
  {
    "code": "620100",
    "name": "兰州市",
    "level": "city",
    "parentCode": "620000",
    "center": [
      103.823557,
      36.058039
    ],
    "province": "甘肃省"
  },
  {
    "code": "620200",
    "name": "嘉峪关市",
    "level": "city",
    "parentCode": "620000",
    "center": [
      98.277304,
      39.786529
    ],
    "province": "甘肃省"
  },
  {
    "code": "620300",
    "name": "金昌市",
    "level": "city",
    "parentCode": "620000",
    "center": [
      102.187888,
      38.514238
    ],
    "province": "甘肃省"
  },
  {
    "code": "620400",
    "name": "白银市",
    "level": "city",
    "parentCode": "620000",
    "center": [
      104.173606,
      36.54568
    ],
    "province": "甘肃省"
  },
  {
    "code": "620500",
    "name": "天水市",
    "level": "city",
    "parentCode": "620000",
    "center": [
      105.724998,
      34.578529
    ],
    "province": "甘肃省"
  },
  {
    "code": "620600",
    "name": "武威市",
    "level": "city",
    "parentCode": "620000",
    "center": [
      102.634697,
      37.929996
    ],
    "province": "甘肃省"
  },
  {
    "code": "620700",
    "name": "张掖市",
    "level": "city",
    "parentCode": "620000",
    "center": [
      100.455472,
      38.932897
    ],
    "province": "甘肃省"
  },
  {
    "code": "620800",
    "name": "平凉市",
    "level": "city",
    "parentCode": "620000",
    "center": [
      106.684691,
      35.54279
    ],
    "province": "甘肃省"
  },
  {
    "code": "620900",
    "name": "酒泉市",
    "level": "city",
    "parentCode": "620000",
    "center": [
      98.510795,
      39.744023
    ],
    "province": "甘肃省"
  },
  {
    "code": "621000",
    "name": "庆阳市",
    "level": "city",
    "parentCode": "620000",
    "center": [
      107.638372,
      35.734218
    ],
    "province": "甘肃省"
  },
  {
    "code": "621100",
    "name": "定西市",
    "level": "city",
    "parentCode": "620000",
    "center": [
      104.626294,
      35.579578
    ],
    "province": "甘肃省"
  },
  {
    "code": "621200",
    "name": "陇南市",
    "level": "city",
    "parentCode": "620000",
    "center": [
      104.929379,
      33.388598
    ],
    "province": "甘肃省"
  },
  {
    "code": "622900",
    "name": "临夏回族自治州",
    "level": "city",
    "parentCode": "620000",
    "center": [
      103.212006,
      35.599446
    ],
    "province": "甘肃省"
  },
  {
    "code": "623000",
    "name": "甘南藏族自治州",
    "level": "city",
    "parentCode": "620000",
    "center": [
      102.911008,
      34.986354
    ],
    "province": "甘肃省"
  },
  {
    "code": "630100",
    "name": "西宁市",
    "level": "city",
    "parentCode": "630000",
    "center": [
      101.778916,
      36.623178
    ],
    "province": "青海省"
  },
  {
    "code": "630200",
    "name": "海东市",
    "level": "city",
    "parentCode": "630000",
    "center": [
      102.10327,
      36.502916
    ],
    "province": "青海省"
  },
  {
    "code": "632200",
    "name": "海北藏族自治州",
    "level": "city",
    "parentCode": "630000",
    "center": [
      100.901059,
      36.959435
    ],
    "province": "青海省"
  },
  {
    "code": "632300",
    "name": "黄南藏族自治州",
    "level": "city",
    "parentCode": "630000",
    "center": [
      102.019988,
      35.517744
    ],
    "province": "青海省"
  },
  {
    "code": "632500",
    "name": "海南藏族自治州",
    "level": "city",
    "parentCode": "630000",
    "center": [
      100.619542,
      36.280353
    ],
    "province": "青海省"
  },
  {
    "code": "632600",
    "name": "果洛藏族自治州",
    "level": "city",
    "parentCode": "630000",
    "center": [
      100.242143,
      34.4736
    ],
    "province": "青海省"
  },
  {
    "code": "632700",
    "name": "玉树藏族自治州",
    "level": "city",
    "parentCode": "630000",
    "center": [
      97.008522,
      33.004049
    ],
    "province": "青海省"
  },
  {
    "code": "632800",
    "name": "海西蒙古族藏族自治州",
    "level": "city",
    "parentCode": "630000",
    "center": [
      97.370785,
      37.374663
    ],
    "province": "青海省"
  },
  {
    "code": "640100",
    "name": "银川市",
    "level": "city",
    "parentCode": "640000",
    "center": [
      106.278179,
      38.46637
    ],
    "province": "宁夏回族自治区"
  },
  {
    "code": "640200",
    "name": "石嘴山市",
    "level": "city",
    "parentCode": "640000",
    "center": [
      106.376173,
      39.01333
    ],
    "province": "宁夏回族自治区"
  },
  {
    "code": "640300",
    "name": "吴忠市",
    "level": "city",
    "parentCode": "640000",
    "center": [
      106.199409,
      37.986165
    ],
    "province": "宁夏回族自治区"
  },
  {
    "code": "640400",
    "name": "固原市",
    "level": "city",
    "parentCode": "640000",
    "center": [
      106.285241,
      36.004561
    ],
    "province": "宁夏回族自治区"
  },
  {
    "code": "640500",
    "name": "中卫市",
    "level": "city",
    "parentCode": "640000",
    "center": [
      105.189568,
      37.514951
    ],
    "province": "宁夏回族自治区"
  },
  {
    "code": "650100",
    "name": "乌鲁木齐市",
    "level": "city",
    "parentCode": "650000",
    "center": [
      87.617733,
      43.792818
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "650200",
    "name": "克拉玛依市",
    "level": "city",
    "parentCode": "650000",
    "center": [
      84.873946,
      45.595886
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "650400",
    "name": "吐鲁番市",
    "level": "city",
    "parentCode": "650000",
    "center": [
      89.184078,
      42.947613
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "650500",
    "name": "哈密市",
    "level": "city",
    "parentCode": "650000",
    "center": [
      93.51316,
      42.833248
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "652300",
    "name": "昌吉回族自治州",
    "level": "city",
    "parentCode": "650000",
    "center": [
      87.304012,
      44.014577
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "652700",
    "name": "博尔塔拉蒙古自治州",
    "level": "city",
    "parentCode": "650000",
    "center": [
      82.074778,
      44.903258
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "652800",
    "name": "巴音郭楞蒙古自治州",
    "level": "city",
    "parentCode": "650000",
    "center": [
      86.150969,
      41.768552
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "652900",
    "name": "阿克苏地区",
    "level": "city",
    "parentCode": "650000",
    "center": [
      80.265068,
      41.170712
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "653000",
    "name": "克孜勒苏柯尔克孜自治州",
    "level": "city",
    "parentCode": "650000",
    "center": [
      76.172825,
      39.713431
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "653100",
    "name": "喀什地区",
    "level": "city",
    "parentCode": "650000",
    "center": [
      75.989138,
      39.467664
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "653200",
    "name": "和田地区",
    "level": "city",
    "parentCode": "650000",
    "center": [
      79.92533,
      37.110687
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "654000",
    "name": "伊犁哈萨克自治州",
    "level": "city",
    "parentCode": "650000",
    "center": [
      81.317946,
      43.92186
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "654200",
    "name": "塔城地区",
    "level": "city",
    "parentCode": "650000",
    "center": [
      82.985732,
      46.746301
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "654300",
    "name": "阿勒泰地区",
    "level": "city",
    "parentCode": "650000",
    "center": [
      88.13963,
      47.848393
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "659001",
    "name": "石河子市",
    "level": "city",
    "parentCode": "650000",
    "center": [
      86.041075,
      44.305886
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "659002",
    "name": "阿拉尔市",
    "level": "city",
    "parentCode": "650000",
    "center": [
      81.285884,
      40.541914
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "659003",
    "name": "图木舒克市",
    "level": "city",
    "parentCode": "650000",
    "center": [
      79.077978,
      39.867316
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "659004",
    "name": "五家渠市",
    "level": "city",
    "parentCode": "650000",
    "center": [
      87.526884,
      44.167401
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "659005",
    "name": "北屯市",
    "level": "city",
    "parentCode": "650000",
    "center": [
      87.824932,
      47.353177
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "659006",
    "name": "铁门关市",
    "level": "city",
    "parentCode": "650000",
    "center": [
      85.501218,
      41.827251
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "659007",
    "name": "双河市",
    "level": "city",
    "parentCode": "650000",
    "center": [
      82.353656,
      44.840524
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "659008",
    "name": "可克达拉市",
    "level": "city",
    "parentCode": "650000",
    "center": [
      80.63579,
      43.6832
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "659009",
    "name": "昆玉市",
    "level": "city",
    "parentCode": "650000",
    "center": [
      79.287372,
      37.207994
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "659010",
    "name": "胡杨河市",
    "level": "city",
    "parentCode": "650000",
    "center": [
      84.8275959,
      44.69288853
    ],
    "province": "新疆维吾尔自治区"
  },
  {
    "code": "810001",
    "name": "中西区",
    "level": "county",
    "parentCode": "810000",
    "center": [
      114.1543731,
      22.28198083
    ],
    "province": "香港特别行政区"
  },
  {
    "code": "810002",
    "name": "湾仔区",
    "level": "county",
    "parentCode": "810000",
    "center": [
      114.1829153,
      22.27638889
    ],
    "province": "香港特别行政区"
  },
  {
    "code": "810003",
    "name": "东区",
    "level": "county",
    "parentCode": "810000",
    "center": [
      114.2260031,
      22.27969306
    ],
    "province": "香港特别行政区"
  },
  {
    "code": "810004",
    "name": "南区",
    "level": "county",
    "parentCode": "810000",
    "center": [
      114.1600117,
      22.24589667
    ],
    "province": "香港特别行政区"
  },
  {
    "code": "810005",
    "name": "油尖旺区",
    "level": "county",
    "parentCode": "810000",
    "center": [
      114.1733317,
      22.31170389
    ],
    "province": "香港特别行政区"
  },
  {
    "code": "810006",
    "name": "深水埗区",
    "level": "county",
    "parentCode": "810000",
    "center": [
      114.1632417,
      22.33385417
    ],
    "province": "香港特别行政区"
  },
  {
    "code": "810007",
    "name": "九龙城区",
    "level": "county",
    "parentCode": "810000",
    "center": [
      114.1928467,
      22.31251
    ],
    "province": "香港特别行政区"
  },
  {
    "code": "810008",
    "name": "黄大仙区",
    "level": "county",
    "parentCode": "810000",
    "center": [
      114.2038856,
      22.33632056
    ],
    "province": "香港特别行政区"
  },
  {
    "code": "810009",
    "name": "观塘区",
    "level": "county",
    "parentCode": "810000",
    "center": [
      114.2140542,
      22.32083778
    ],
    "province": "香港特别行政区"
  },
  {
    "code": "810010",
    "name": "荃湾区",
    "level": "county",
    "parentCode": "810000",
    "center": [
      114.1210792,
      22.36830667
    ],
    "province": "香港特别行政区"
  },
  {
    "code": "810011",
    "name": "屯门区",
    "level": "county",
    "parentCode": "810000",
    "center": [
      113.9765742,
      22.39384417
    ],
    "province": "香港特别行政区"
  },
  {
    "code": "810012",
    "name": "元朗区",
    "level": "county",
    "parentCode": "810000",
    "center": [
      114.0324381,
      22.44142833
    ],
    "province": "香港特别行政区"
  },
  {
    "code": "810013",
    "name": "北区",
    "level": "county",
    "parentCode": "810000",
    "center": [
      114.1473639,
      22.49610389
    ],
    "province": "香港特别行政区"
  },
  {
    "code": "810014",
    "name": "大埔区",
    "level": "county",
    "parentCode": "810000",
    "center": [
      114.1717431,
      22.44565306
    ],
    "province": "香港特别行政区"
  },
  {
    "code": "810015",
    "name": "西贡区",
    "level": "county",
    "parentCode": "810000",
    "center": [
      114.264645,
      22.31421306
    ],
    "province": "香港特别行政区"
  },
  {
    "code": "810016",
    "name": "沙田区",
    "level": "county",
    "parentCode": "810000",
    "center": [
      114.1953653,
      22.37953167
    ],
    "province": "香港特别行政区"
  },
  {
    "code": "810017",
    "name": "葵青区",
    "level": "county",
    "parentCode": "810000",
    "center": [
      114.1393194,
      22.36387667
    ],
    "province": "香港特别行政区"
  },
  {
    "code": "810018",
    "name": "离岛区",
    "level": "county",
    "parentCode": "810000",
    "center": [
      113.94612,
      22.28640778
    ],
    "province": "香港特别行政区"
  },
  {
    "code": "820001",
    "name": "花地玛堂区",
    "level": "county",
    "parentCode": "820000",
    "center": [
      113.5528956,
      22.20787
    ],
    "province": "澳门特别行政区"
  },
  {
    "code": "820002",
    "name": "花王堂区",
    "level": "county",
    "parentCode": "820000",
    "center": [
      113.5489608,
      22.1992075
    ],
    "province": "澳门特别行政区"
  },
  {
    "code": "820003",
    "name": "望德堂区",
    "level": "county",
    "parentCode": "820000",
    "center": [
      113.5501828,
      22.19372083
    ],
    "province": "澳门特别行政区"
  },
  {
    "code": "820004",
    "name": "大堂区",
    "level": "county",
    "parentCode": "820000",
    "center": [
      113.5536475,
      22.18853944
    ],
    "province": "澳门特别行政区"
  },
  {
    "code": "820005",
    "name": "风顺堂区",
    "level": "county",
    "parentCode": "820000",
    "center": [
      113.5419278,
      22.18736806
    ],
    "province": "澳门特别行政区"
  },
  {
    "code": "820006",
    "name": "嘉模堂区",
    "level": "county",
    "parentCode": "820000",
    "center": [
      113.5587044,
      22.15375944
    ],
    "province": "澳门特别行政区"
  },
  {
    "code": "820007",
    "name": "路凼填海区",
    "level": "county",
    "parentCode": "820000",
    "center": [
      113.5695992,
      22.13663
    ],
    "province": "澳门特别行政区"
  },
  {
    "code": "820008",
    "name": "圣方济各堂区",
    "level": "county",
    "parentCode": "820000",
    "center": [
      113.5599542,
      22.12348639
    ],
    "province": "澳门特别行政区"
  }
];
